'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'
import { Link } from '@/i18n/navigation'
import type { AISeoContent } from '@/lib/aiSeoContent'

const copy = {
  no: {
    whatIsLabel: 'Definisjoner',
    whatIsTitle: 'Hva er AI SEO?',
    whyLabel: 'Endringen',
    whyTitle: 'Hvorfor tradisjonell SEO ikke er nok alene',
    whyIntro: 'Klassisk SEO er fortsatt nødvendig – men det er ikke lenger tilstrekkelig alene. Når svaret genereres av en modell i stedet for hentet fra en liste med lenker, endrer det hva som faktisk teller.',
    tableDimension: 'Dimensjon',
    tableTraditional: 'Tradisjonell SEO',
    tableAi: 'AI-søk (GEO)',
    linkSeo: 'klassisk søkemotoroptimalisering',
    seoSentencePrefix: 'God AI SEO forutsetter en solid teknisk grunnmur. Vi bygger den gjennom vårt arbeid med ',
    seoSentenceSuffix: ', og legger AI-laget oppå.',
    automationSentence: 'Økt AI-synlighet gir flere henvendelser. Kombinert med',
    automationLinkLabel: 'AI-automasjon',
    automationSentenceSuffix: 'sikrer du at ingen av dem blir liggende ubesvart.',
    frameworkLabel: 'Metodikk',
    frameworkTitle: 'Vårt AI SEO-rammeverk',
    frameworkIntro: 'Elleve arbeidsområder som til sammen avgjør om AI-systemer finner, forstår og siterer bedriften din. Se også konkrete resultater fra',
    frameworkLinkLabel: 'kundeprosjektene våre',
    frameworkSuffix: '.',
  },
  en: {
    whatIsLabel: 'Definitions',
    whatIsTitle: 'What is AI SEO?',
    whyLabel: 'The shift',
    whyTitle: 'Why traditional SEO is no longer enough on its own',
    whyIntro: 'Classic SEO is still necessary — but it is no longer sufficient by itself. When the answer is generated by a model instead of retrieved from a list of links, what actually counts changes.',
    tableDimension: 'Dimension',
    tableTraditional: 'Traditional SEO',
    tableAi: 'AI search (GEO)',
    linkSeo: 'classic search engine optimisation',
    seoSentencePrefix: 'Good AI SEO assumes a solid technical foundation. We build it through our work on ',
    seoSentenceSuffix: ', then layer AI signals on top.',
    automationSentence: 'Higher AI visibility means more enquiries. Combined with',
    automationLinkLabel: 'AI automation',
    automationSentenceSuffix: 'you make sure none of them go unanswered.',
    frameworkLabel: 'Methodology',
    frameworkTitle: 'Our AI SEO framework',
    frameworkIntro: 'Eleven areas of work that together decide whether AI systems find, understand and cite your business. See real results in',
    frameworkLinkLabel: 'our client projects',
    frameworkSuffix: '.',
  },
} as const

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center gap-2 text-accent text-xs font-semibold uppercase tracking-widest mb-4">
      <span className="w-4 h-px bg-accent" /> {children}
    </span>
  )
}

export default function AISeoSections({ content, lang }: { content: AISeoContent; lang: 'no' | 'en' }) {
  const t = copy[lang]

  const defsRef = useRef(null)
  const defsInView = useInView(defsRef, { once: true, margin: '-80px' })
  const whyRef = useRef(null)
  const whyInView = useInView(whyRef, { once: true, margin: '-80px' })
  const frameworkRef = useRef(null)
  const frameworkInView = useInView(frameworkRef, { once: true, margin: '-80px' })

  const definitions = [
    { term: content.definitions.aiSeoTerm, body: content.definitions.aiSeo },
    { term: content.definitions.geoTerm, body: content.definitions.geo },
    { term: content.definitions.aeoTerm, body: content.definitions.aeo },
  ]

  return (
    <>
      {/* What is AI SEO? */}
      <section ref={defsRef} className="py-14 md:py-20 lg:py-24 px-6 lg:px-8 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={defsInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5 }}
            className="mb-12 max-w-3xl"
          >
            <Eyebrow>{t.whatIsLabel}</Eyebrow>
            <h2 className="display-text text-3xl sm:text-4xl text-fg mb-5">{t.whatIsTitle}</h2>
            <p className="text-fg-muted leading-relaxed">{content.howSearchChanged.body}</p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
            {definitions.map((d, i) => (
              <motion.div
                key={d.term}
                initial={{ opacity: 0, y: 20 }}
                animate={defsInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.45, delay: 0.1 + i * 0.1 }}
                className="bg-bg-2 border border-border rounded-xl p-6"
              >
                <h3 className="font-semibold text-fg mb-2.5">{d.term}</h3>
                <p className="text-fg-muted text-sm leading-relaxed">{d.body}</p>
              </motion.div>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={defsInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.4, delay: 0.45 }}
            className="flex flex-wrap gap-2"
          >
            {content.howSearchChanged.engines.map((engine) => (
              <span
                key={engine}
                className="text-xs font-medium text-fg-muted bg-white border border-border px-3 py-1.5 rounded-full"
              >
                {engine}
              </span>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Why traditional SEO is no longer enough */}
      <section ref={whyRef} className="py-14 md:py-20 lg:py-24 px-6 lg:px-8 bg-bg-2">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={whyInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5 }}
            className="mb-10 max-w-3xl"
          >
            <Eyebrow>{t.whyLabel}</Eyebrow>
            <h2 className="display-text text-3xl sm:text-4xl text-fg mb-5">{t.whyTitle}</h2>
            <p className="text-fg-muted leading-relaxed">{t.whyIntro}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={whyInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, delay: 0.15 }}
            className="bg-white border border-border rounded-xl overflow-hidden shadow-card mb-8"
          >
            <div className="overflow-x-auto">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-bg-2 border-b border-border">
                    <th scope="col" className="text-left font-semibold text-fg-muted text-xs uppercase tracking-widest px-5 py-3.5 whitespace-nowrap">{t.tableDimension}</th>
                    <th scope="col" className="text-left font-semibold text-fg-muted text-xs uppercase tracking-widest px-5 py-3.5">{t.tableTraditional}</th>
                    <th scope="col" className="text-left font-semibold text-accent text-xs uppercase tracking-widest px-5 py-3.5">{t.tableAi}</th>
                  </tr>
                </thead>
                <tbody>
                  {content.comparison.map((row, i) => (
                    <tr key={row.dimension} className={i < content.comparison.length - 1 ? 'border-b border-border' : ''}>
                      <th scope="row" className="text-left font-semibold text-fg px-5 py-4 align-top whitespace-nowrap">{row.dimension}</th>
                      <td className="text-fg-muted px-5 py-4 align-top leading-relaxed">{row.traditional}</td>
                      <td className="text-fg px-5 py-4 align-top leading-relaxed">{row.aiSearch}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </motion.div>

          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={whyInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.4, delay: 0.3 }}
            className="text-fg-muted text-sm leading-relaxed max-w-3xl"
          >
            {t.seoSentencePrefix}
            <Link href="/tjenester/seo" className="text-accent font-medium hover:underline">{t.linkSeo}</Link>
            {t.seoSentenceSuffix}{' '}
            {t.automationSentence}{' '}
            <Link href="/tjenester/ai-automasjon" className="text-accent font-medium hover:underline">{t.automationLinkLabel}</Link>{' '}
            {t.automationSentenceSuffix}
          </motion.p>
        </div>
      </section>

      {/* Framework */}
      <section ref={frameworkRef} className="py-14 md:py-20 lg:py-24 px-6 lg:px-8 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={frameworkInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5 }}
            className="mb-12 max-w-3xl"
          >
            <Eyebrow>{t.frameworkLabel}</Eyebrow>
            <h2 className="display-text text-3xl sm:text-4xl text-fg mb-5">{t.frameworkTitle}</h2>
            <p className="text-fg-muted leading-relaxed">
              {t.frameworkIntro}{' '}
              <Link href="/prosjekter" className="text-accent font-medium hover:underline">{t.frameworkLinkLabel}</Link>
              {t.frameworkSuffix}
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {content.framework.map((pillar, i) => (
              <motion.div
                key={pillar.number}
                initial={{ opacity: 0, y: 20 }}
                animate={frameworkInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.45, delay: 0.06 * i }}
                className="bg-bg-2 border border-border rounded-xl p-7"
              >
                <p className="display-text text-3xl text-accent/25 mb-4">{pillar.number}</p>
                <h3 className="font-semibold text-fg mb-2.5">{pillar.title}</h3>
                <p className="text-fg-muted text-sm leading-relaxed">{pillar.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
