import type { ServiceContent } from '@/lib/serviceContent'

export type { ServiceContent as IndustryContent }

export const tannlege: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for tannlege Bergen – bestilling | Frameflow',
      description: 'Nettside for tannlegeklinikker i Bergen med timebestilling, pasientomtaler og lokal SEO innebygd. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for tannlege i Bergen | Frameflow',
      ogImageTitle: 'Nettside for tannleger i Bergen',
      ogImageLabel: 'Tannlege',
      ogAlt: 'Nettside for tannlege Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/tannlege',
    },
    label: 'Bransje',
    title: 'Nettside for tannlege i Bergen',
    description: 'En tannlegeklinikk lever av tillit og tilgjengelighet. Vi bygger nettsider som gjør det enkelt for pasienter å bestille time, se behandlingene deres og finne klinikken på Google – uten teknisk hodepine for deg.',
    longDescription: 'De fleste pasienter velger tannlege basert på hva de finner på Google og hvor lett det er å bestille time. En nettside for en tannlegeklinikk må derfor gjøre tre ting godt: bygge tillit gjennom profesjonelle bilder og pasientomtaler, gjøre timebestilling enkelt nok til at pasienten faktisk fullfører den, og rangere lokalt når folk søker «tannlege» pluss bydelen sin. Vi bygger nettsiden rundt akkurat disse tre målene, med lokal SEO og en trygg, GDPR-sikker løsning for pasienthenvendelser innebygd fra dag én.',
    includes: [
      'Integrasjon med timebestillingssystem',
      'Presentasjon av behandlinger og priser',
      'Bilder av klinikk og team som bygger tillit',
      'Google-anmeldelser og pasientomtaler',
      'Tydelig CTA for akutt tannlegehjelp',
      'GDPR-sikkert kontaktskjema for pasienthenvendelser',
      'Lokal SEO for bydeler i Bergen',
      'Mobilvennlig design for søk på farten',
    ],
    process: [
      { step: '01', title: 'Kartlegging av klinikken', description: 'Vi kartlegger behandlingstilbudet, timebestillingssystemet dere allerede bruker og hvilke bydeler dere vil nå med lokal SEO.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som gjør timebestilling enkelt, viser frem klinikken på en tillitvekkende måte og er teknisk optimalisert for Google fra start.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på lokale søk og henvendelser, slik at dere ser at nettsiden faktisk gir nye pasienter.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en tannlegeklinikk?', a: 'En skreddersydd nettside for en tannlegeklinikk starter fra 15 000 kr eks. mva. Prisen avhenger av antall sider, om dere trenger integrasjon mot et eksisterende timebestillingssystem, og omfanget av innhold. Vi gir alltid fast pris før oppstart.' },
      { q: 'Kan pasienter bestille time direkte på nettsiden?', a: 'Ja. Vi integrerer med timebestillingssystemet klinikken allerede bruker, eller setter opp et enkelt bestillingsskjema hvis dere ikke har et system fra før. Målet er at pasienten kan bestille time på under ett minutt.' },
      { q: 'Er nettsiden trygg for pasientopplysninger?', a: 'Ja. Kontaktskjemaer bygges med kryptert overføring og uten unødvendig lagring av helseopplysninger, i tråd med GDPR. Vi går gjennom akkurat hvilken informasjon som samles inn og hvorfor før nettsiden lanseres.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard klinikknettside tar typisk 3–5 uker fra oppstart til lansering, avhengig av hvor raskt vi får tilgang til bilder, tekster og eventuell integrasjon mot timebestillingssystem.' },
      { q: 'Kan vi vise frem pasientomtaler på nettsiden?', a: 'Ja, og vi anbefaler det sterkt – pasientomtaler er noe av det som påvirker valg av tannlege mest. Vi henter inn Google-anmeldelser automatisk eller viser frem utvalgte omtaler dere har fått tillatelse til å dele.' },
      { q: 'Hjelper dere med lokal SEO for tannleger i Bergen?', a: 'Ja, det er en kjerneleveranse. Vi optimaliserer for søk som «tannlege Bergenhus» eller «tannlege Åsane», setter opp Google Business Profile riktig, og sørger for at NAP-informasjonen (navn, adresse, telefon) er konsistent overalt.' },
    ],
  },
  en: {
    meta: {
      title: 'Dentist website Bergen – booking & SEO | Frameflow',
      description: 'Websites for dental clinics with online booking, patient reviews and local SEO built in. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Dentist website in Bergen | Frameflow',
      ogImageTitle: 'Websites for dental clinics',
      ogImageLabel: 'Dentist',
      ogAlt: 'Dentist website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/dentist',
    },
    label: 'Industry',
    title: 'Website for dentists in Bergen',
    description: 'A dental clinic lives on trust and accessibility. We build websites that make it easy for patients to book an appointment, see your treatments, and find the clinic on Google — without the technical headache for you.',
    longDescription: 'Most patients choose a dentist based on what they find on Google and how easy it is to book an appointment. A dental clinic website therefore needs to do three things well: build trust through professional photos and patient reviews, make booking simple enough that patients actually complete it, and rank locally when people search "dentist" plus their neighbourhood. We build the website around exactly these three goals, with local SEO and a secure, GDPR-compliant approach to patient enquiries built in from day one.',
    includes: [
      'Integration with your booking system',
      'Clear presentation of treatments and pricing',
      'Clinic and team photos that build trust',
      'Google reviews and patient testimonials',
      'Clear call-to-action for urgent dental care',
      'GDPR-secure contact form for patient enquiries',
      'Local SEO for Bergen neighbourhoods',
      'Mobile-friendly design for on-the-go searches',
    ],
    process: [
      { step: '01', title: 'Mapping the clinic', description: 'We map your treatment offering, the booking system you already use, and which neighbourhoods you want to reach with local SEO.' },
      { step: '02', title: 'Design and development', description: 'We build a website that makes booking simple, presents the clinic in a trust-building way, and is technically optimised for Google from the start.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on local searches and enquiries, so you can see the website is actually bringing in new patients.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a dental clinic website cost?', a: 'A custom website for a dental clinic starts from NOK 15,000 excl. VAT. The price depends on the number of pages, whether you need integration with an existing booking system, and the scope of content. We always give a fixed price before starting.' },
      { q: 'Can patients book appointments directly on the website?', a: 'Yes. We integrate with the booking system your clinic already uses, or set up a simple booking form if you don’t have one. The goal is that a patient can book an appointment in under a minute.' },
      { q: 'Is the website secure for patient information?', a: 'Yes. Contact forms are built with encrypted transmission and without unnecessary storage of health data, in line with GDPR. We review exactly what information is collected and why before the site launches.' },
      { q: 'How long does it take to build the website?', a: 'A standard clinic website typically takes 3–5 weeks from start to launch, depending on how quickly we receive photos, copy, and any booking-system integration.' },
      { q: 'Can we show patient reviews on the website?', a: 'Yes, and we strongly recommend it — patient reviews are one of the biggest factors in choosing a dentist. We pull in Google reviews automatically or feature selected testimonials you have permission to share.' },
      { q: 'Do you help with local SEO for dentists in Bergen?', a: 'Yes, it is a core part of the deliverable. We optimise for searches like "dentist Bergenhus" or "dentist Åsane", set up Google Business Profile correctly, and ensure your NAP information (name, address, phone) is consistent everywhere.' },
    ],
  },
}

export const eiendomsmegler: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for eiendomsmegler Bergen | Frameflow',
      description: 'Nettside for eiendomsmeglere i Bergen med boligvisning, verdivurdering-skjema og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for eiendomsmegler i Bergen | Frameflow',
      ogImageTitle: 'Nettside for eiendomsmeglere',
      ogImageLabel: 'Eiendomsmegler',
      ogAlt: 'Nettside for eiendomsmegler Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/eiendomsmegler',
    },
    label: 'Bransje',
    title: 'Nettside for eiendomsmegler i Bergen',
    description: 'Boligkjøpere bestemmer seg raskt – nettsiden din må vise frem boliger på en måte som selger, og gjøre det enkelt for potensielle selgere å be om verdivurdering. Vi bygger nettsider som gjør begge deler.',
    longDescription: 'En eiendomsmeglers nettside har to helt forskjellige besøkende: boligkjøpere som vil se attraktive boliger raskt, og potensielle selgere som vurderer hvem de skal gi oppdraget til. Nettsiden må derfor både presentere boliger på en salgbar måte med bilder og video i høy kvalitet, og bygge nok tillit til at en boligselger tar kontakt for verdivurdering. Vi bygger nettsiden rundt begge målgruppene, med lokal SEO for bydelene dere jobber i og en rask, mobilvennlig opplevelse for boligsøk.',
    includes: [
      'Presentasjon av boliger til salgs',
      'Skjema for gratis verdivurdering',
      'Visningskalender og kontaktpunkt for interessenter',
      'Høykvalitets bilde- og videovisning av boliger',
      'Meglerprofil som bygger tillit',
      'Lokal SEO for bydeler i Bergen',
      'Rask lasting optimalisert for boligsøk på mobil',
      'Integrasjon med annonseringsplattformer',
    ],
    process: [
      { step: '01', title: 'Kartlegging av kontoret', description: 'Vi kartlegger hvilke bydeler dere jobber i, hvordan dere annonserer boliger i dag, og hva som skal til for at en potensiell selger tar kontakt.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som viser frem boliger på en salgbar måte, gjør verdivurdering-skjemaet lett å finne, og er teknisk optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og lokale rangeringer, slik at dere ser hvilke søk som faktisk gir nye oppdrag.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et meglerkontor?', a: 'En skreddersydd nettside for et eiendomsmeglerkontor starter fra 15 000 kr eks. mva. Prisen avhenger av antall sider, hvor mange meglerprofiler som skal presenteres, og om dere trenger integrasjon mot annonseringsplattformer.' },
      { q: 'Kan nettsiden vise boliger til salgs automatisk?', a: 'Ja. Vi setter opp en løsning som presenterer boligene deres tydelig, enten manuelt oppdatert eller integrert med systemet dere allerede annonserer gjennom, avhengig av hva som passer kontoret best.' },
      { q: 'Kan vi ha et skjema for gratis verdivurdering?', a: 'Ja – dette er en av de viktigste elementene på en meglernettside, siden det er hovedveien potensielle selgere tar kontakt på. Vi plasserer det synlig og gjør det raskt å fylle ut.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et meglerkontor tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall meglerprofiler og eventuell integrasjon med annonseringssystemer.' },
      { q: 'Hjelper dere med lokal SEO for eiendomsmeglere i Bergen?', a: 'Ja. Vi optimaliserer for søk som «eiendomsmegler Fana» eller «selge bolig Bergenhus», og sørger for at kontoret rangerer i de bydelene dere faktisk jobber i.' },
      { q: 'Kan dere integrere med boligannonser og visningssystem?', a: 'Ja, vi tilpasser løsningen til det annonseringssystemet eller den plattformen kontoret allerede bruker, slik at boligvisningen på nettsiden alltid er oppdatert.' },
    ],
  },
  en: {
    meta: {
      title: 'Real estate agent website Bergen | Frameflow',
      description: 'Websites for real estate agents in Bergen with property listings, valuation forms and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Real estate agent website in Bergen | Frameflow',
      ogImageTitle: 'Websites for real estate agents',
      ogImageLabel: 'Real estate',
      ogAlt: 'Real estate agent website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/real-estate-agent',
    },
    label: 'Industry',
    title: 'Website for real estate agents in Bergen',
    description: 'Home buyers decide fast — your website needs to present listings in a way that sells, and make it easy for potential sellers to request a valuation. We build websites that do both.',
    longDescription: 'A real estate agent’s website has two very different visitors: buyers who want to see attractive listings quickly, and potential sellers weighing up who to give the assignment to. The website therefore needs to both present listings in a sellable way with high-quality photos and video, and build enough trust that a seller reaches out for a valuation. We build the site around both audiences, with local SEO for the neighbourhoods you work in and a fast, mobile-friendly experience for property search.',
    includes: [
      'Presentation of listings for sale',
      'Free valuation request form',
      'Viewing calendar and contact point for interested buyers',
      'High-quality photo and video display of listings',
      'Agent profile that builds trust',
      'Local SEO for Bergen neighbourhoods',
      'Fast loading optimised for mobile property search',
      'Integration with listing platforms',
    ],
    process: [
      { step: '01', title: 'Mapping the agency', description: 'We map which neighbourhoods you work in, how you currently advertise listings, and what it takes for a potential seller to reach out.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents listings in a sellable way, makes the valuation form easy to find, and is technically optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and local rankings, so you can see which searches are actually bringing in new assignments.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a real estate agency website cost?', a: 'A custom website for a real estate agency starts from NOK 15,000 excl. VAT. The price depends on the number of pages, how many agent profiles need to be presented, and whether you need integration with listing platforms.' },
      { q: 'Can the website display listings automatically?', a: 'Yes. We set up a solution that presents your listings clearly, either manually updated or integrated with the system you already advertise through, depending on what suits the agency best.' },
      { q: 'Can we have a free valuation request form?', a: 'Yes — this is one of the most important elements on an agency website, since it is the main way potential sellers get in touch. We place it prominently and make it quick to fill out.' },
      { q: 'How long does it take to build the website?', a: 'A standard agency website typically takes 3–5 weeks from start to launch, depending on the number of agent profiles and any integration with listing systems.' },
      { q: 'Do you help with local SEO for real estate agents in Bergen?', a: 'Yes. We optimise for searches like "real estate agent Fana" or "sell house Bergenhus", and make sure the agency ranks in the neighbourhoods you actually work in.' },
      { q: 'Can you integrate with listing platforms and viewing systems?', a: 'Yes, we adapt the solution to the listing platform or system the agency already uses, so the property display on the website is always up to date.' },
    ],
  },
}

export const advokat: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for advokat Bergen – lokal SEO | Frameflow',
      description: 'Nettside for advokatfirmaer i Bergen som bygger tillit, presenterer rettsområder tydelig og rangerer lokalt. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for advokat i Bergen | Frameflow',
      ogImageTitle: 'Nettside for advokatfirmaer',
      ogImageLabel: 'Advokat',
      ogAlt: 'Nettside for advokat Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/advokat',
    },
    label: 'Bransje',
    title: 'Nettside for advokat i Bergen',
    description: 'Juridiske tjenester er et tillitsvalg. Nettsiden din må bygge troverdighet fra første sekund, presentere rettsområdene deres tydelig, og gjøre det trygt for potensielle klienter å ta kontakt om sensitive saker.',
    longDescription: 'Å velge advokat er et av de mest tillitsbaserte valgene folk tar – de fleste undersøker firmaet grundig på nett før de tar kontakt. Nettsiden må derfor gjøre tre ting: presentere rettsområdene og advokatenes kompetanse tydelig, bygge troverdighet gjennom ekte bilder, fagartikler og eventuelle kundeomtaler, og gi et trygt, konfidensielt kontaktpunkt for henvendelser om sensitive saker. Vi bygger nettsiden med akkurat dette som utgangspunkt, med lokal SEO for rettsområder og bydeler innebygd.',
    includes: [
      'Tydelig presentasjon av rettsområder',
      'Profilsider for hver advokat med kompetanse og bakgrunn',
      'Konfidensielt kontaktskjema for henvendelser',
      'CTA for gratis eller uforpliktende førstesamtale',
      'Fagartikler og innhold som bygger autoritet',
      'Lokal SEO for rettsområder og bydeler i Bergen',
      'Strukturert data for advokater og rettsområder',
      'Mobilvennlig design for raske henvendelser',
    ],
    process: [
      { step: '01', title: 'Kartlegging av firmaet', description: 'Vi kartlegger rettsområdene deres, hvilke advokater som skal presenteres, og hvilke søk potensielle klienter faktisk bruker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som presenterer kompetansen deres troverdig, gjør kontakt trygt og enkelt, og er teknisk optimalisert for lokale søk innen juss.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og rangeringer, slik at dere ser hvilke rettsområder som faktisk gir nye klienter.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Branding', href: '/tjenester/branding' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et advokatfirma?', a: 'En skreddersydd nettside for et advokatfirma starter fra 15 000 kr eks. mva. Prisen avhenger av antall advokatprofiler, rettsområder som skal presenteres, og om dere ønsker fagartikler som del av leveransen.' },
      { q: 'Kan potensielle klienter ta kontakt konfidensielt via nettsiden?', a: 'Ja. Kontaktskjemaer bygges med kryptert overføring, og vi går gjennom nøyaktig hvilken informasjon som samles inn slik at henvendelser om sensitive saker føles trygge å sende.' },
      { q: 'Kan vi ha egne profilsider for hver advokat?', a: 'Ja, og vi anbefaler det – potensielle klienter vil ofte vite hvem de skal snakke med og hvilken erfaring vedkommende har før de tar kontakt. Hver advokat får en egen profilside med kompetanseområder.' },
      { q: 'Hjelper dere med SEO for advokater i Bergen?', a: 'Ja. Vi optimaliserer for søk som «advokat familierett Bergen» eller «advokat arbeidsrett Åsane», og setter opp strukturert data som gjør det tydelig for Google hvilke rettsområder dere dekker.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et advokatfirma tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall advokatprofiler og om fagartikler skal skrives som del av leveransen.' },
      { q: 'Kan nettsiden bygge tillit for et fagfelt hvor troverdighet er alt?', a: 'Ja – dette er selve utgangspunktet for hvordan vi designer den. Ekte bilder fremfor stockbilder, tydelig presentasjon av erfaring og rettsområder, og fagartikler som viser kompetanse, er alle med på å bygge den tilliten juridiske tjenester er avhengige av.' },
    ],
  },
  en: {
    meta: {
      title: 'Law firm website Bergen – local SEO | Frameflow',
      description: 'Websites for law firms in Bergen that build trust, present practice areas clearly and rank locally. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Law firm website in Bergen | Frameflow',
      ogImageTitle: 'Websites for law firms',
      ogImageLabel: 'Law firm',
      ogAlt: 'Law firm website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/lawyer',
    },
    label: 'Industry',
    title: 'Website for law firms in Bergen',
    description: 'Legal services are a trust decision. Your website needs to build credibility from the first second, present your practice areas clearly, and make it safe for potential clients to reach out about sensitive matters.',
    longDescription: 'Choosing a lawyer is one of the most trust-based decisions people make — most research the firm thoroughly online before making contact. The website therefore needs to do three things: present practice areas and each lawyer’s expertise clearly, build credibility through real photos, articles and any client testimonials, and provide a safe, confidential point of contact for enquiries about sensitive matters. We build the website with exactly this as the starting point, with local SEO for practice areas and neighbourhoods built in.',
    includes: [
      'Clear presentation of practice areas',
      'Profile pages for each lawyer with expertise and background',
      'Confidential contact form for enquiries',
      'Call-to-action for a free or no-obligation initial consultation',
      'Articles and content that build authority',
      'Local SEO for practice areas and Bergen neighbourhoods',
      'Structured data for lawyers and practice areas',
      'Mobile-friendly design for quick enquiries',
    ],
    process: [
      { step: '01', title: 'Mapping the firm', description: 'We map your practice areas, which lawyers should be presented, and what searches potential clients actually use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents your expertise credibly, makes contact safe and easy, and is technically optimised for local legal searches.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and rankings, so you can see which practice areas are actually bringing in new clients.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Branding', href: '/tjenester/branding' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a law firm website cost?', a: 'A custom website for a law firm starts from NOK 15,000 excl. VAT. The price depends on the number of lawyer profiles, practice areas to be presented, and whether you want articles included as part of the delivery.' },
      { q: 'Can potential clients get in touch confidentially through the website?', a: 'Yes. Contact forms are built with encrypted transmission, and we review exactly what information is collected so enquiries about sensitive matters feel safe to send.' },
      { q: 'Can we have individual profile pages for each lawyer?', a: 'Yes, and we recommend it — potential clients often want to know who they will be speaking with and what experience they have before making contact. Each lawyer gets their own profile page with areas of expertise.' },
      { q: 'Do you help with SEO for lawyers in Bergen?', a: 'Yes. We optimise for searches like "family law lawyer Bergen" or "employment lawyer Åsane", and set up structured data that makes it clear to Google which practice areas you cover.' },
      { q: 'How long does it take to build the website?', a: 'A standard law firm website typically takes 3–5 weeks from start to launch, depending on the number of lawyer profiles and whether articles are written as part of the delivery.' },
      { q: 'Can the website build trust for a field where credibility is everything?', a: 'Yes — this is the actual starting point for how we design it. Real photos instead of stock images, clear presentation of experience and practice areas, and articles that demonstrate expertise all help build the trust legal services depend on.' },
    ],
  },
}

export const restaurant: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for restaurant Bergen – bordbestilling | Frameflow',
      description: 'Nettside for restauranter i Bergen med bordbestilling, meny og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for restaurant i Bergen | Frameflow',
      ogImageTitle: 'Nettside for restauranter',
      ogImageLabel: 'Restaurant',
      ogAlt: 'Nettside for restaurant Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/restaurant',
    },
    label: 'Bransje',
    title: 'Nettside for restaurant i Bergen',
    description: 'De fleste gjester bestemmer seg for en restaurant basert på bilder, meny og hvor lett det er å bestille bord. Vi bygger nettsider som gjør akkurat det – raskt, visuelt og enkelt å oppdatere selv.',
    longDescription: 'En restaurantgjest tar som regel beslutningen på mobilen, ofte rett før de skal spise. Nettsiden må derfor laste raskt, vise frem menyen og maten på en fristende måte, og gjøre bordbestilling så enkelt at gjesten faktisk fullfører den i stedet for å ringe et annet sted. Vi bygger nettsiden rundt dette, med integrasjon mot bestillings- og leveringsløsninger, sosiale medier og lokal SEO for søk som «restaurant» pluss bydel eller matkategori.',
    includes: [
      'Bordbestilling integrert på nettsiden',
      'Meny som er enkel å oppdatere selv',
      'Profesjonelle bilder av mat og lokale',
      'Åpningstider og lokasjon tydelig synlig',
      'Integrasjon med levering (Wolt, Foodora m.fl.)',
      'Instagram-feed og sosiale medier-integrasjon',
      'Lokal SEO for bydeler og matkategori',
      'Rask lasting optimalisert for mobil',
    ],
    process: [
      { step: '01', title: 'Kartlegging av restauranten', description: 'Vi kartlegger konseptet, menyen, bestillings- og leveringsløsningene dere bruker, og hvilke søk gjestene faktisk skriver inn på Google.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som viser frem maten fristende, gjør bordbestilling raskt, og er teknisk optimalisert for lokale søk og rask lasting på mobil.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på bestillinger og lokale søk, slik at dere ser hva som faktisk fyller bordene.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
      { title: 'Sosiale medier', href: '/tjenester/sosiale-medier' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en restaurant?', a: 'En skreddersydd nettside for en restaurant starter fra 15 000 kr eks. mva. Prisen avhenger av om dere trenger bordbestillingsintegrasjon, hvor mange sider dere ønsker, og omfanget av foto/video.' },
      { q: 'Kan gjester bestille bord direkte på nettsiden?', a: 'Ja. Vi integrerer med bordbestillingssystemet dere allerede bruker, eller setter opp en enkel løsning hvis dere ikke har en fra før, slik at gjesten bestiller bord uten å måtte ringe.' },
      { q: 'Kan vi oppdatere menyen selv?', a: 'Ja, det er en forutsetning. Menyen bygges slik at dere selv kan endre retter og priser når som helst, uten å måtte kontakte en utvikler.' },
      { q: 'Hjelper dere med lokal SEO for restauranter i Bergen?', a: 'Ja. Vi optimaliserer for søk som «restaurant Bryggen» eller «sushi Bergen sentrum», og setter opp Google Business Profile med riktige åpningstider og bilder.' },
      { q: 'Kan dere integrere levering og sosiale medier?', a: 'Ja, vi kobler på levering gjennom Wolt, Foodora eller lignende tjenester, og setter opp en Instagram-feed direkte på nettsiden slik at den alltid viser ferskt innhold.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard restaurantnettside tar typisk 3–5 uker fra oppstart til lansering, avhengig av bordbestillingsintegrasjon og hvor raskt vi får bilder og menyinnhold.' },
    ],
  },
  en: {
    meta: {
      title: 'Restaurant website Bergen – table booking | Frameflow',
      description: 'Websites for restaurants in Bergen with table booking, menu and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Restaurant website in Bergen | Frameflow',
      ogImageTitle: 'Websites for restaurants',
      ogImageLabel: 'Restaurant',
      ogAlt: 'Restaurant website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/restaurant',
    },
    label: 'Industry',
    title: 'Website for restaurants in Bergen',
    description: 'Most guests decide on a restaurant based on photos, the menu and how easy it is to book a table. We build websites that do exactly that — fast, visual and easy to update yourself.',
    longDescription: 'A restaurant guest usually makes the decision on their phone, often right before they want to eat. The website therefore needs to load fast, present the menu and food in an appetising way, and make table booking simple enough that the guest actually completes it instead of calling somewhere else. We build the website around this, with integration for ordering/delivery platforms, social media, and local SEO for searches like "restaurant" plus neighbourhood or cuisine type.',
    includes: [
      'Table booking integrated on the website',
      'Menu that is easy to update yourself',
      'Professional photos of food and interior',
      'Opening hours and location clearly visible',
      'Integration with delivery (Wolt, Foodora, etc.)',
      'Instagram feed and social media integration',
      'Local SEO for neighbourhoods and cuisine type',
      'Fast loading optimised for mobile',
    ],
    process: [
      { step: '01', title: 'Mapping the restaurant', description: 'We map your concept, menu, the ordering and delivery platforms you use, and what guests actually search for on Google.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents the food appetisingly, makes table booking fast, and is technically optimised for local search and fast mobile loading.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on bookings and local searches, so you can see what is actually filling the tables.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
      { title: 'Social media', href: '/tjenester/sosiale-medier' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a restaurant website cost?', a: 'A custom website for a restaurant starts from NOK 15,000 excl. VAT. The price depends on whether you need table-booking integration, how many pages you want, and the scope of photo/video.' },
      { q: 'Can guests book a table directly on the website?', a: 'Yes. We integrate with the table-booking system you already use, or set up a simple solution if you don’t have one, so guests can book without having to call.' },
      { q: 'Can we update the menu ourselves?', a: 'Yes, that is a requirement. The menu is built so you can change dishes and prices yourself at any time, without contacting a developer.' },
      { q: 'Do you help with local SEO for restaurants in Bergen?', a: 'Yes. We optimise for searches like "restaurant Bryggen" or "sushi Bergen city centre", and set up Google Business Profile with correct opening hours and photos.' },
      { q: 'Can you integrate delivery and social media?', a: 'Yes, we connect delivery through Wolt, Foodora or similar services, and set up an Instagram feed directly on the website so it always shows fresh content.' },
      { q: 'How long does it take to build the website?', a: 'A standard restaurant website typically takes 3–5 weeks from start to launch, depending on table-booking integration and how quickly we receive photos and menu content.' },
    ],
  },
}

export const frisor: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for frisør Bergen – bestilling | Frameflow',
      description: 'Nettside for frisør- og skjønnhetssalonger i Bergen med timebestilling, prisliste og bildegalleri. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for frisør i Bergen | Frameflow',
      ogImageTitle: 'Nettside for frisørsalonger',
      ogImageLabel: 'Frisør',
      ogAlt: 'Nettside for frisør Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/frisor',
    },
    label: 'Bransje',
    title: 'Nettside for frisør i Bergen',
    description: 'En frisør- eller skjønnhetssalong lever av å vise frem arbeidet sitt og gjøre det raskt å bestille time. Vi bygger nettsider som gjør begge deler, med bildegalleri og bestilling innebygd.',
    longDescription: 'De fleste kunder velger salong basert på bilder av tidligere arbeid og hvor enkelt det er å bestille time – helst uten å måtte ringe. Nettsiden må derfor vise frem frisyrer og behandlinger på en fristende måte, gjøre timebestilling raskt, og gjerne la kunden velge en bestemt frisør eller behandler. Vi bygger nettsiden rundt dette, med Instagram-integrasjon og lokal SEO for bydeler og tjenestetyper innebygd.',
    includes: [
      'Timebestilling integrert på nettsiden',
      'Prisliste og tjenesteoversikt',
      'Bildegalleri av frisyrer og behandlinger',
      'Profiler for hver frisør eller behandler',
      'Instagram-feed direkte på nettsiden',
      'Salg av gavekort',
      'Lokal SEO for bydeler og tjenestetyper',
      'Mobilvennlig for rask bestilling',
    ],
    process: [
      { step: '01', title: 'Kartlegging av salongen', description: 'Vi kartlegger tjenestene, hvor mange ansatte som skal presenteres, og hvilket bestillingssystem dere bruker eller ønsker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som viser frem arbeidet på en fristende måte, gjør bestilling raskt, og er teknisk optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på bestillinger og lokale søk, slik at dere ser hva som faktisk fyller timeboken.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
      { title: 'Sosiale medier', href: '/tjenester/sosiale-medier' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en frisørsalong?', a: 'En skreddersydd nettside for en frisør- eller skjønnhetssalong starter fra 15 000 kr eks. mva. Prisen avhenger av om dere trenger bestillingsintegrasjon, hvor mange ansatte som skal presenteres, og omfanget av bildegalleri.' },
      { q: 'Kan kunder bestille time direkte på nettsiden?', a: 'Ja. Vi integrerer med bestillingssystemet dere allerede bruker, eller setter opp en enkel løsning hvis dere ikke har en fra før.' },
      { q: 'Kan vi vise frem before/after-bilder av arbeidet vårt?', a: 'Ja, og vi anbefaler det sterkt – bilder av tidligere arbeid er noe av det som påvirker valg av salong mest. Vi bygger et bildegalleri som er enkelt å oppdatere selv.' },
      { q: 'Kan kundene velge en bestemt frisør ved bestilling?', a: 'Ja. Vi setter opp profiler for hver ansatt slik at kunden kan velge hvem de vil bestille time hos, om det er ønskelig for salongen.' },
      { q: 'Hjelper dere med lokal SEO for frisører i Bergen?', a: 'Ja. Vi optimaliserer for søk som «frisør Bergenhus» eller «negler Åsane», og setter opp Google Business Profile med riktige åpningstider og bilder.' },
      { q: 'Kan vi selge gavekort på nettsiden?', a: 'Ja, det er en vanlig og god inntektskilde for salonger. Vi setter opp en enkel løsning for salg av gavekort direkte på nettsiden.' },
    ],
  },
  en: {
    meta: {
      title: 'Hairdresser website Bergen – booking | Frameflow',
      description: 'Websites for hair and beauty salons in Bergen with booking, pricing and a photo gallery. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Hairdresser website in Bergen | Frameflow',
      ogImageTitle: 'Websites for hair salons',
      ogImageLabel: 'Hairdresser',
      ogAlt: 'Hairdresser website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/hairdresser',
    },
    label: 'Industry',
    title: 'Website for hairdressers in Bergen',
    description: 'A hair or beauty salon lives on showing off its work and making it fast to book an appointment. We build websites that do both, with a photo gallery and booking built in.',
    longDescription: 'Most clients choose a salon based on photos of previous work and how easy it is to book an appointment — ideally without having to call. The website therefore needs to present styles and treatments in an appealing way, make booking fast, and ideally let the client choose a specific stylist or therapist. We build the website around this, with Instagram integration and local SEO for neighbourhoods and treatment types built in.',
    includes: [
      'Booking integrated on the website',
      'Price list and service overview',
      'Photo gallery of styles and treatments',
      'Profiles for each stylist or therapist',
      'Instagram feed directly on the website',
      'Gift card sales',
      'Local SEO for neighbourhoods and treatment types',
      'Mobile-friendly for fast booking',
    ],
    process: [
      { step: '01', title: 'Mapping the salon', description: 'We map your services, how many staff should be presented, and the booking system you use or want.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents your work appealingly, makes booking fast, and is technically optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on bookings and local searches, so you can see what is actually filling the calendar.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
      { title: 'Social media', href: '/tjenester/sosiale-medier' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a hairdresser website cost?', a: 'A custom website for a hair or beauty salon starts from NOK 15,000 excl. VAT. The price depends on whether you need booking integration, how many staff should be presented, and the scope of the photo gallery.' },
      { q: 'Can clients book appointments directly on the website?', a: 'Yes. We integrate with the booking system you already use, or set up a simple solution if you don’t have one.' },
      { q: 'Can we show before/after photos of our work?', a: 'Yes, and we strongly recommend it — photos of previous work are one of the biggest factors in choosing a salon. We build a photo gallery that is easy to update yourself.' },
      { q: 'Can clients choose a specific stylist when booking?', a: 'Yes. We set up profiles for each staff member so clients can choose who they want to book with, if that’s something the salon wants.' },
      { q: 'Do you help with local SEO for hairdressers in Bergen?', a: 'Yes. We optimise for searches like "hairdresser Bergenhus" or "nails Åsane", and set up Google Business Profile with correct opening hours and photos.' },
      { q: 'Can we sell gift cards on the website?', a: 'Yes, it’s a common and effective revenue source for salons. We set up a simple solution for gift card sales directly on the website.' },
    ],
  },
}

export const fysioterapeut: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for fysioterapeut Bergen | Frameflow',
      description: 'Nettside for fysioterapiklinikker i Bergen med timebestilling, behandlertilbud og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for fysioterapeut i Bergen | Frameflow',
      ogImageTitle: 'Nettside for fysioterapiklinikker',
      ogImageLabel: 'Fysioterapeut',
      ogAlt: 'Nettside for fysioterapeut Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/fysioterapeut',
    },
    label: 'Bransje',
    title: 'Nettside for fysioterapeut i Bergen',
    description: 'Pasienter velger fysioterapeut basert på hvilke plager klinikken behandler og hvor enkelt det er å bestille time. Vi bygger nettsider som gjør begge deler tydelige.',
    longDescription: 'En fysioterapiklinikk har ofte flere behandlere med ulik spesialisering – idrettsskader, ryggplager, rehabilitering etter operasjon. Nettsiden må presentere dette tydelig, gjøre timebestilling enkelt, og bygge tillit gjennom ekte bilder og pasientomtaler. Vi bygger nettsiden med akkurat dette som utgangspunkt, med et trygt kontaktskjema for pasienthenvendelser og lokal SEO for bydeler og skadetyper.',
    includes: [
      'Integrasjon med timebestillingssystem',
      'Presentasjon av behandlere og spesialiseringer',
      'Tydelig oversikt over behandlingstilbud',
      'Pasientomtaler og Google-anmeldelser',
      'GDPR-sikkert kontaktskjema for pasienthenvendelser',
      'Lokal SEO for bydeler og skadetyper',
      'Informasjon om henvisning og egenandel',
      'Mobilvennlig design',
    ],
    process: [
      { step: '01', title: 'Kartlegging av klinikken', description: 'Vi kartlegger behandlerne, spesialiseringene og timebestillingssystemet dere bruker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som presenterer behandlingstilbudet tydelig, gjør bestilling enkelt, og er optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og lokale søk.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en fysioterapiklinikk?', a: 'En skreddersydd nettside for en fysioterapiklinikk starter fra 15 000 kr eks. mva. Prisen avhenger av antall behandlerprofiler og om dere trenger integrasjon mot timebestillingssystem.' },
      { q: 'Kan pasienter bestille time direkte på nettsiden?', a: 'Ja. Vi integrerer med systemet klinikken allerede bruker, eller setter opp en enkel bestillingsløsning.' },
      { q: 'Er nettsiden trygg for pasientopplysninger?', a: 'Ja. Kontaktskjemaer bygges med kryptert overføring og uten unødvendig lagring av helseopplysninger, i tråd med GDPR.' },
      { q: 'Kan vi presentere behandlere med egne spesialiseringer?', a: 'Ja, og vi anbefaler det – pasienter vil ofte finne en behandler med relevant erfaring for akkurat deres plage før de bestiller time.' },
      { q: 'Hjelper dere med lokal SEO for fysioterapeuter i Bergen?', a: 'Ja. Vi optimaliserer for søk som «fysioterapeut ryggplager Bergen» eller «idrettsfysioterapi Åsane».' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard klinikknettside tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall behandlerprofiler og om dere trenger integrasjon mot timebestillingssystem.' },
    ],
  },
  en: {
    meta: {
      title: 'Physiotherapist website Bergen | Frameflow',
      description: 'Websites for physiotherapy clinics in Bergen with booking, treatment overview and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Physiotherapist website in Bergen | Frameflow',
      ogImageTitle: 'Websites for physiotherapy clinics',
      ogImageLabel: 'Physiotherapist',
      ogAlt: 'Physiotherapist website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/physiotherapist',
    },
    label: 'Industry',
    title: 'Website for physiotherapists in Bergen',
    description: 'Patients choose a physiotherapist based on which conditions the clinic treats and how easy it is to book an appointment. We build websites that make both clear.',
    longDescription: 'A physiotherapy clinic often has several therapists with different specialisations — sports injuries, back pain, post-surgery rehabilitation. The website needs to present this clearly, make booking simple, and build trust through real photos and patient reviews. We build the website with exactly this as the starting point, with a secure contact form for patient enquiries and local SEO for neighbourhoods and injury types.',
    includes: [
      'Integration with your booking system',
      'Presentation of therapists and specialisations',
      'Clear overview of treatment offerings',
      'Patient testimonials and Google reviews',
      'GDPR-secure contact form for patient enquiries',
      'Local SEO for neighbourhoods and injury types',
      'Information on referrals and co-payment',
      'Mobile-friendly design',
    ],
    process: [
      { step: '01', title: 'Mapping the clinic', description: 'We map your therapists, specialisations, and the booking system you use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents your treatment offering clearly, makes booking simple, and is optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and local searches.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a physiotherapy clinic website cost?', a: 'A custom website for a physiotherapy clinic starts from NOK 15,000 excl. VAT. The price depends on the number of therapist profiles and whether you need booking-system integration.' },
      { q: 'Can patients book appointments directly on the website?', a: 'Yes. We integrate with the system your clinic already uses, or set up a simple booking solution.' },
      { q: 'Is the website secure for patient information?', a: 'Yes. Contact forms are built with encrypted transmission and without unnecessary storage of health data, in line with GDPR.' },
      { q: 'Can we present therapists with their own specialisations?', a: 'Yes, and we recommend it — patients often want to find a therapist with relevant experience for their specific condition before booking.' },
      { q: 'Do you help with local SEO for physiotherapists in Bergen?', a: 'Yes. We optimise for searches like "physiotherapist back pain Bergen" or "sports physiotherapy Åsane".' },
      { q: 'How long does it take to build the website?', a: 'A standard clinic website typically takes 3–5 weeks from start to launch, depending on the number of therapist profiles and whether you need booking-system integration.' },
    ],
  },
}

export const handverker: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for håndverker Bergen – tilbud | Frameflow',
      description: 'Nettside for håndverkere i Bergen med referanseprosjekter, tilbudsskjema og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for håndverker i Bergen | Frameflow',
      ogImageTitle: 'Nettside for håndverksfirmaer',
      ogImageLabel: 'Håndverker',
      ogAlt: 'Nettside for håndverker Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/handverker',
    },
    label: 'Bransje',
    title: 'Nettside for håndverker i Bergen',
    description: 'Kunder velger håndverker basert på referanseprosjekter og hvor lett det er å be om tilbud. Vi bygger nettsider som viser frem arbeidet deres og gjør det enkelt å ta kontakt.',
    longDescription: 'De fleste som trenger en håndverker sjekker referanseprosjekter og anmeldelser før de ber om tilbud. Nettsiden må derfor vise frem tidligere arbeid med bilder, gjøre det tydelig hvilke jobber dere tar, og gjøre det raskt å be om tilbud eller ringe ved akutte oppdrag. Vi bygger nettsiden rundt dette, med sertifiseringer og godkjenninger synlig, og lokal SEO for tjenestetype og bydel.',
    includes: [
      'Referanseprosjekter med bilder',
      'Tydelig tjenesteoversikt',
      'Tilbudsskjema for nye oppdrag',
      'Synlige sertifiseringer og godkjenninger',
      'Kundeomtaler',
      'Tydelig CTA for akutte oppdrag',
      'Lokal SEO for tjenestetype og bydel',
      'Mobilvennlig for rask kontakt',
    ],
    process: [
      { step: '01', title: 'Kartlegging av firmaet', description: 'Vi kartlegger tjenestene, sertifiseringene og hvilke referanseprosjekter som skal presenteres.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som viser frem arbeidet troverdig, gjør det raskt å be om tilbud, og er optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og lokale søk.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et håndverksfirma?', a: 'En skreddersydd nettside for et håndverksfirma starter fra 15 000 kr eks. mva. Prisen avhenger av antall referanseprosjekter og omfanget av innhold.' },
      { q: 'Kan vi vise frem referanseprosjekter med bilder?', a: 'Ja, og vi anbefaler det sterkt – referanseprosjekter er det som overbeviser flest kunder. Vi bygger et galleri som er enkelt å oppdatere selv.' },
      { q: 'Kan kunder be om tilbud direkte på nettsiden?', a: 'Ja. Vi setter opp et tilbudsskjema som er raskt å fylle ut, slik at potensielle kunder tar kontakt uten å måtte ringe først.' },
      { q: 'Hjelper dere med lokal SEO for håndverkere i Bergen?', a: 'Ja. Vi optimaliserer for søk som «elektriker Åsane» eller «rørlegger akutt Bergen».' },
      { q: 'Kan vi ha en tydelig CTA for akutte oppdrag?', a: 'Ja, dette er spesielt viktig for elektrikere og rørleggere. Vi plasserer et tydelig nødnummer eller akutt-CTA øverst på nettsiden.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et håndverksfirma tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall referanseprosjekter som skal presenteres og omfanget av tjenesteoversikten.' },
    ],
  },
  en: {
    meta: {
      title: 'Tradesperson website Bergen – quotes | Frameflow',
      description: 'Websites for tradespeople in Bergen with project references, quote forms and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Tradesperson website in Bergen | Frameflow',
      ogImageTitle: 'Websites for trade businesses',
      ogImageLabel: 'Tradesperson',
      ogAlt: 'Tradesperson website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/tradesperson',
    },
    label: 'Industry',
    title: 'Website for tradespeople in Bergen',
    description: 'Customers choose a tradesperson based on project references and how easy it is to request a quote. We build websites that showcase your work and make it easy to get in touch.',
    longDescription: 'Most people who need a tradesperson check project references and reviews before requesting a quote. The website therefore needs to showcase previous work with photos, make it clear which jobs you take on, and make it fast to request a quote or call for urgent jobs. We build the website around this, with certifications and approvals visible, and local SEO for service type and neighbourhood.',
    includes: [
      'Project references with photos',
      'Clear service overview',
      'Quote request form for new jobs',
      'Visible certifications and approvals',
      'Customer reviews',
      'Clear call-to-action for urgent jobs',
      'Local SEO for service type and neighbourhood',
      'Mobile-friendly for quick contact',
    ],
    process: [
      { step: '01', title: 'Mapping the business', description: 'We map your services, certifications, and which project references should be presented.' },
      { step: '02', title: 'Design and development', description: 'We build a website that showcases your work credibly, makes requesting a quote fast, and is optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and local searches.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a tradesperson website cost?', a: 'A custom website for a trade business starts from NOK 15,000 excl. VAT. The price depends on the number of project references and the scope of content.' },
      { q: 'Can we show project references with photos?', a: 'Yes, and we strongly recommend it — project references are what convinces most customers. We build a gallery that is easy to update yourself.' },
      { q: 'Can customers request a quote directly on the website?', a: 'Yes. We set up a quote form that is quick to fill out, so potential customers get in touch without having to call first.' },
      { q: 'Do you help with local SEO for tradespeople in Bergen?', a: 'Yes. We optimise for searches like "electrician Åsane" or "emergency plumber Bergen".' },
      { q: 'Can we have a clear call-to-action for urgent jobs?', a: 'Yes, this is especially important for electricians and plumbers. We place a clear emergency number or CTA at the top of the website.' },
      { q: 'How long does it take to build the website?', a: 'A standard trade business website typically takes 3–5 weeks from start to launch, depending on the number of project references to present and the scope of the service overview.' },
    ],
  },
}

export const regnskapsforer: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for regnskapsfører Bergen | Frameflow',
      description: 'Nettside for regnskapsførere og regnskapsbyråer i Bergen som bygger tillit og rangerer lokalt. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for regnskapsfører i Bergen | Frameflow',
      ogImageTitle: 'Nettside for regnskapsførere',
      ogImageLabel: 'Regnskapsfører',
      ogAlt: 'Nettside for regnskapsfører Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/regnskapsforer',
    },
    label: 'Bransje',
    title: 'Nettside for regnskapsfører i Bergen',
    description: 'Å velge regnskapsfører er et tillitsvalg. Nettsiden din må presentere tjenestene tydelig, vise frem bransjeerfaringen deres, og gjøre det enkelt for potensielle kunder å be om et uforpliktende tilbud.',
    longDescription: 'De fleste bedrifter som bytter regnskapsfører undersøker firmaet grundig først – autorisasjon, bransjeerfaring og hva andre kunder sier. Nettsiden må derfor presentere tjenestene tydelig, fremheve bransjer dere har spesialkompetanse på, og gjøre det trygt og enkelt å ta kontakt for en uforpliktende samtale. Vi bygger nettsiden med akkurat dette som utgangspunkt, med lokal SEO innebygd.',
    includes: [
      'Tydelig presentasjon av tjenester',
      'Fremheving av bransjeerfaring og spesialkompetanse',
      'Kontaktskjema for uforpliktende tilbud',
      'Synlig autorisasjon og seriøsitet',
      'Fagartikler som bygger autoritet',
      'Kundeomtaler',
      'Lokal SEO for regnskapsfører-søk i Bergen',
      'Mobilvennlig design',
    ],
    process: [
      { step: '01', title: 'Kartlegging av firmaet', description: 'Vi kartlegger tjenestene, hvilke bransjer dere har mest erfaring med, og hvordan potensielle kunder faktisk søker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som presenterer kompetansen troverdig og er optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og rangeringer.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Branding', href: '/tjenester/branding' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et regnskapsførerfirma?', a: 'En skreddersydd nettside for et regnskapsførerfirma starter fra 15 000 kr eks. mva. Prisen avhenger av antall sider og om dere ønsker fagartikler som del av leveransen.' },
      { q: 'Kan potensielle kunder be om et uforpliktende tilbud?', a: 'Ja. Vi setter opp et enkelt kontaktskjema der potensielle kunder raskt kan be om en uforpliktende samtale eller tilbud.' },
      { q: 'Hjelper dere med SEO for regnskapsførere i Bergen?', a: 'Ja. Vi optimaliserer for søk som «regnskapsfører byggebransjen Bergen» eller «regnskapsbyrå Åsane».' },
      { q: 'Kan vi fremheve bransjer vi har spesialkompetanse på?', a: 'Ja, og vi anbefaler det – mange bedrifter foretrekker en regnskapsfører med erfaring fra akkurat deres bransje.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et regnskapsførerfirma tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall sider og om dere ønsker fagartikler som del av leveransen.' },
      { q: 'Kan nettsiden bygge tillit for en tjeneste som handler om økonomi?', a: 'Ja – det er utgangspunktet for designet. Tydelig presentasjon av autorisasjon, erfaring og kundeomtaler bygger den tilliten regnskapstjenester er avhengige av.' },
    ],
  },
  en: {
    meta: {
      title: 'Accountant website Bergen | Frameflow',
      description: 'Websites for accounting firms in Bergen that build trust and rank locally. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Accountant website in Bergen | Frameflow',
      ogImageTitle: 'Websites for accounting firms',
      ogImageLabel: 'Accountant',
      ogAlt: 'Accountant website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/accountant',
    },
    label: 'Industry',
    title: 'Website for accountants in Bergen',
    description: 'Choosing an accountant is a trust decision. Your website needs to present services clearly, showcase your industry experience, and make it easy for potential clients to request a no-obligation quote.',
    longDescription: 'Most businesses switching accountants research the firm thoroughly first — authorisation, industry experience and what other clients say. The website therefore needs to present services clearly, highlight industries you specialise in, and make it safe and easy to reach out for a no-obligation conversation. We build the website with exactly this as the starting point, with local SEO built in.',
    includes: [
      'Clear presentation of services',
      'Highlighting industry experience and specialisation',
      'Contact form for no-obligation quotes',
      'Visible authorisation and credibility',
      'Articles that build authority',
      'Client testimonials',
      'Local SEO for accountant searches in Bergen',
      'Mobile-friendly design',
    ],
    process: [
      { step: '01', title: 'Mapping the firm', description: 'We map your services, which industries you have the most experience with, and what potential clients actually search for.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents your expertise credibly and is optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and rankings.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Branding', href: '/tjenester/branding' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does an accounting firm website cost?', a: 'A custom website for an accounting firm starts from NOK 15,000 excl. VAT. The price depends on the number of pages and whether you want articles included as part of the delivery.' },
      { q: 'Can potential clients request a no-obligation quote?', a: 'Yes. We set up a simple contact form where potential clients can quickly request a no-obligation conversation or quote.' },
      { q: 'Do you help with SEO for accountants in Bergen?', a: 'Yes. We optimise for searches like "accountant construction industry Bergen" or "accounting firm Åsane".' },
      { q: 'Can we highlight industries we specialise in?', a: 'Yes, and we recommend it — many businesses prefer an accountant with experience in their specific industry.' },
      { q: 'How long does it take to build the website?', a: 'A standard accounting firm website typically takes 3–5 weeks from start to launch, depending on the number of pages and whether you want articles included.' },
      { q: 'Can the website build trust for a service centred on finances?', a: 'Yes — that is the starting point for the design. Clear presentation of authorisation, experience and client testimonials builds the trust accounting services depend on.' },
    ],
  },
}

export const treningssenter: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for treningssenter Bergen | Frameflow',
      description: 'Nettside for treningssentre i Bergen med medlemskap, timeplan og prøvetime. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for treningssenter i Bergen | Frameflow',
      ogImageTitle: 'Nettside for treningssentre',
      ogImageLabel: 'Treningssenter',
      ogAlt: 'Nettside for treningssenter Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/treningssenter',
    },
    label: 'Bransje',
    title: 'Nettside for treningssenter i Bergen',
    description: 'De fleste bestemmer seg for et treningssenter basert på pris, timeplan og hvor lett det er å booke en prøvetime. Vi bygger nettsider som gjør akkurat det tydelig og raskt.',
    longDescription: 'En besøkende som vurderer et treningssenter vil raskt finne prisplaner, se timeplanen for gruppetimer, og gjerne booke en prøvetime uten å måtte ringe. Nettsiden må derfor presentere medlemskap tydelig, vise frem lokalet og utstyret, og gjøre innmelding eller prøvetime-booking enkel. Vi bygger nettsiden rundt dette, med Instagram-integrasjon og lokal SEO innebygd.',
    includes: [
      'Prisplaner og medlemskap tydelig presentert',
      'Timeplan for gruppetimer, enkel å oppdatere',
      'Booking av prøvetime direkte på nettsiden',
      'Bilder og video av lokalet og utstyret',
      'Trenerprofiler for PT-booking',
      'Instagram-feed og sosiale medier-integrasjon',
      'Lokal SEO for bydeler i Bergen',
      'Mobilvennlig for rask påmelding',
    ],
    process: [
      { step: '01', title: 'Kartlegging av senteret', description: 'Vi kartlegger medlemskapstyper, gruppetimer og hvilket system dere bruker for booking i dag.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som gjør innmelding og prøvetime-booking raskt, og er optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på innmeldinger og lokale søk.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Sosiale medier', href: '/tjenester/sosiale-medier' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et treningssenter?', a: 'En skreddersydd nettside for et treningssenter starter fra 15 000 kr eks. mva. Prisen avhenger av om dere trenger integrasjon mot medlemssystem og omfanget av innhold.' },
      { q: 'Kan besøkende melde seg inn eller booke prøvetime direkte?', a: 'Ja. Vi setter opp en løsning for innmelding eller prøvetime-booking direkte på nettsiden, eller integrerer med systemet dere allerede bruker.' },
      { q: 'Kan vi vise timeplan for gruppetimer som er enkel å oppdatere?', a: 'Ja, det er en forutsetning. Dere kan endre timeplanen selv når som helst, uten å kontakte en utvikler.' },
      { q: 'Hjelper dere med lokal SEO for treningssentre i Bergen?', a: 'Ja. Vi optimaliserer for søk som «treningssenter Bergenhus» eller «gruppetimer Åsane».' },
      { q: 'Kan kundene booke personlig trener på nettsiden?', a: 'Ja. Vi setter opp trenerprofiler slik at kundene kan velge og booke PT-timer direkte.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et treningssenter tar typisk 3–5 uker fra oppstart til lansering, avhengig av om dere trenger integrasjon mot medlemssystem og omfanget av innhold.' },
    ],
  },
  en: {
    meta: {
      title: 'Gym website Bergen – bookings | Frameflow',
      description: 'Websites for gyms in Bergen with membership plans, class schedules and free trial bookings. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Gym website in Bergen | Frameflow',
      ogImageTitle: 'Websites for gyms',
      ogImageLabel: 'Gym',
      ogAlt: 'Gym website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/gym',
    },
    label: 'Industry',
    title: 'Website for gyms in Bergen',
    description: 'Most people decide on a gym based on price, class schedule and how easy it is to book a free trial. We build websites that make exactly that clear and fast.',
    longDescription: 'Someone considering a gym wants to quickly find membership plans, see the class schedule, and ideally book a free trial without having to call. The website therefore needs to present membership clearly, showcase the facility and equipment, and make signing up or booking a trial easy. We build the website around this, with Instagram integration and local SEO built in.',
    includes: [
      'Membership plans clearly presented',
      'Class schedule, easy to update',
      'Free trial booking directly on the website',
      'Photos and video of the facility and equipment',
      'Trainer profiles for PT booking',
      'Instagram feed and social media integration',
      'Local SEO for Bergen neighbourhoods',
      'Mobile-friendly for fast sign-up',
    ],
    process: [
      { step: '01', title: 'Mapping the gym', description: 'We map your membership types, classes, and the booking system you currently use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that makes sign-up and trial booking fast, and is optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on sign-ups and local searches.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Social media', href: '/tjenester/sosiale-medier' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a gym website cost?', a: 'A custom website for a gym starts from NOK 15,000 excl. VAT. The price depends on whether you need membership-system integration and the scope of content.' },
      { q: 'Can visitors sign up or book a free trial directly?', a: 'Yes. We set up a solution for sign-up or trial booking directly on the website, or integrate with the system you already use.' },
      { q: 'Can we show a class schedule that is easy to update?', a: 'Yes, that is a requirement. You can change the schedule yourself at any time, without contacting a developer.' },
      { q: 'Do you help with local SEO for gyms in Bergen?', a: 'Yes. We optimise for searches like "gym Bergenhus" or "group classes Åsane".' },
      { q: 'Can clients book a personal trainer on the website?', a: 'Yes. We set up trainer profiles so clients can choose and book PT sessions directly.' },
      { q: 'How long does it take to build the website?', a: 'A standard gym website typically takes 3–5 weeks from start to launch, depending on whether you need membership-system integration and the scope of content.' },
    ],
  },
}

export const bilverksted: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for bilverksted Bergen | Frameflow',
      description: 'Nettside for bilverksteder i Bergen med timebestilling, prisoverslag og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for bilverksted i Bergen | Frameflow',
      ogImageTitle: 'Nettside for bilverksteder',
      ogImageLabel: 'Bilverksted',
      ogAlt: 'Nettside for bilverksted Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/bilverksted',
    },
    label: 'Bransje',
    title: 'Nettside for bilverksted i Bergen',
    description: 'Å velge bilverksted handler om tillit – de fleste vil unngå å bli overfakturert. Vi bygger nettsider som viser frem tjenestene tydelig og gjør det enkelt å bestille time eller be om prisoverslag.',
    longDescription: 'De fleste som trenger service eller reparasjon søker etter et verksted nær seg, ofte akutt – etter en punktering eller en varsellampe som lyser. Nettsiden må derfor laste raskt, gjøre timebestilling enkelt, og bygge tillit gjennom tydelige priser og ekte kundeomtaler. Vi bygger nettsiden rundt dette, med lokal SEO for bydeler og tjenestetyper innebygd.',
    includes: [
      'Timebestilling for service integrert på nettsiden',
      'Tydelig tjenesteoversikt',
      'Skjema for prisoverslag',
      'Kundeomtaler som bygger tillit',
      'Synlig spesialisering på bilmerker',
      'Åpningstider og lokasjon tydelig',
      'Lokal SEO for tjenestetype og bydel',
      'Mobilvennlig for akutte søk',
    ],
    process: [
      { step: '01', title: 'Kartlegging av verkstedet', description: 'Vi kartlegger tjenestene, eventuell merkespesialisering, og hvilket bestillingssystem dere bruker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som gjør timebestilling raskt, bygger tillit, og er optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på bestillinger og lokale søk.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et bilverksted?', a: 'En skreddersydd nettside for et bilverksted starter fra 15 000 kr eks. mva. Prisen avhenger av om dere trenger integrasjon mot bestillingssystem og omfanget av tjenester som skal presenteres.' },
      { q: 'Kan kunder bestille time for service direkte på nettsiden?', a: 'Ja. Vi integrerer med bestillingssystemet dere allerede bruker, eller setter opp en enkel løsning.' },
      { q: 'Kan vi ha et skjema for prisoverslag?', a: 'Ja. Dette gjør det enkelt for potensielle kunder å få en pekepinn på pris før de bestiller time.' },
      { q: 'Hjelper dere med lokal SEO for bilverksteder i Bergen?', a: 'Ja. Vi optimaliserer for søk som «bilverksted Åsane» eller «dekkskift Bergen».' },
      { q: 'Kan vi vise frem kundeomtaler for å bygge tillit?', a: 'Ja, og vi anbefaler det sterkt – tillit er den viktigste faktoren når folk velger bilverksted.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et bilverksted tar typisk 3–5 uker fra oppstart til lansering, avhengig av om dere trenger integrasjon mot bestillingssystem og omfanget av tjenester som skal presenteres.' },
    ],
  },
  en: {
    meta: {
      title: 'Auto repair shop website Bergen | Frameflow',
      description: 'Websites for auto repair shops in Bergen with service booking, price estimates and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Auto repair shop website in Bergen | Frameflow',
      ogImageTitle: 'Websites for auto repair shops',
      ogImageLabel: 'Auto repair',
      ogAlt: 'Auto repair shop website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/auto-repair-shop',
    },
    label: 'Industry',
    title: 'Website for auto repair shops in Bergen',
    description: 'Choosing an auto repair shop is about trust — most people want to avoid being overcharged. We build websites that present services clearly and make it easy to book a service or request an estimate.',
    longDescription: 'Most people who need service or repairs search for a nearby shop, often urgently — after a flat tyre or a warning light. The website therefore needs to load fast, make booking simple, and build trust through clear pricing and real customer reviews. We build the website around this, with local SEO for neighbourhoods and service types built in.',
    includes: [
      'Service booking integrated on the website',
      'Clear service overview',
      'Price estimate request form',
      'Customer reviews that build trust',
      'Visible brand specialisation',
      'Opening hours and location clearly visible',
      'Local SEO for service type and neighbourhood',
      'Mobile-friendly for urgent searches',
    ],
    process: [
      { step: '01', title: 'Mapping the shop', description: 'We map your services, any brand specialisation, and the booking system you use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that makes booking fast, builds trust, and is optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on bookings and local searches.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does an auto repair shop website cost?', a: 'A custom website for an auto repair shop starts from NOK 15,000 excl. VAT. The price depends on whether you need booking-system integration and the scope of services presented.' },
      { q: 'Can customers book a service appointment directly?', a: 'Yes. We integrate with the booking system you already use, or set up a simple solution.' },
      { q: 'Can we have a price estimate request form?', a: 'Yes. This makes it easy for potential customers to get a sense of price before booking.' },
      { q: 'Do you help with local SEO for auto repair shops in Bergen?', a: 'Yes. We optimise for searches like "auto repair shop Åsane" or "tyre change Bergen".' },
      { q: 'Can we show customer reviews to build trust?', a: 'Yes, and we strongly recommend it — trust is the biggest factor when people choose an auto repair shop.' },
      { q: 'How long does it take to build the website?', a: 'A standard auto repair shop website typically takes 3–5 weeks from start to launch, depending on whether you need booking-system integration and the scope of services presented.' },
    ],
  },
}

export const veterinaer: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for veterinær Bergen – akutt | Frameflow',
      description: 'Nettside for veterinærklinikker i Bergen med timebestilling, akutt-kontakt og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for veterinær i Bergen | Frameflow',
      ogImageTitle: 'Nettside for veterinærklinikker',
      ogImageLabel: 'Veterinær',
      ogAlt: 'Nettside for veterinær Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/veterinaer',
    },
    label: 'Bransje',
    title: 'Nettside for veterinær i Bergen',
    description: 'Dyreeiere er ofte bekymret når de leter etter veterinær, og vil raskt vite hvordan de når dere ved akutte tilfeller. Vi bygger nettsider som roer ned og gjør kontakt enkel.',
    longDescription: 'En dyreeier som søker etter veterinær er ofte bekymret for kjæledyret sitt. Nettsiden må derfor bygge trygghet gjennom ekte bilder av klinikken og teamet, gjøre det krystallklart hvordan man når dere ved akutte tilfeller, og gjøre timebestilling enkel for vanlige kontroller og vaksinasjoner. Vi bygger nettsiden med akkurat dette som utgangspunkt, med lokal SEO innebygd.',
    includes: [
      'Timebestilling for kontroll og vaksinasjon',
      'Tydelig akutt-kontakt og nødtelefon',
      'Presentasjon av behandlingstilbud',
      'Bilder av klinikk og team som bygger trygghet',
      'Omtaler fra dyreeiere',
      'GDPR-sikkert kontaktskjema',
      'Lokal SEO for bydeler i Bergen',
      'Mobilvennlig for raske henvendelser',
    ],
    process: [
      { step: '01', title: 'Kartlegging av klinikken', description: 'Vi kartlegger behandlingstilbudet, akuttrutinene og timebestillingssystemet dere bruker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som bygger trygghet, gjør akutt-kontakt tydelig, og er optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og lokale søk.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en veterinærklinikk?', a: 'En skreddersydd nettside for en veterinærklinikk starter fra 15 000 kr eks. mva. Prisen avhenger av antall sider og om dere trenger integrasjon mot timebestillingssystem.' },
      { q: 'Kan dyreeiere bestille time direkte på nettsiden?', a: 'Ja. Vi integrerer med timebestillingssystemet klinikken bruker, eller setter opp en enkel bestillingsløsning.' },
      { q: 'Er det tydelig hvordan man når dere ved akutte tilfeller?', a: 'Ja, dette prioriterer vi høyt i designet. Nødtelefon og akutt-informasjon plasseres synlig øverst på nettsiden.' },
      { q: 'Hjelper dere med lokal SEO for veterinærer i Bergen?', a: 'Ja. Vi optimaliserer for søk som «veterinær akutt Bergen» eller «dyreklinikk Åsane».' },
      { q: 'Kan vi vise frem omtaler fra dyreeiere?', a: 'Ja, og vi anbefaler det – omtaler fra andre dyreeiere bygger tillit hos bekymrede kunder.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard klinikknettside tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall sider og om dere trenger integrasjon mot timebestillingssystem.' },
    ],
  },
  en: {
    meta: {
      title: 'Veterinary clinic website Bergen | Frameflow',
      description: 'Websites for veterinary clinics in Bergen with booking, emergency contact and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Veterinary clinic website in Bergen | Frameflow',
      ogImageTitle: 'Websites for veterinary clinics',
      ogImageLabel: 'Veterinarian',
      ogAlt: 'Veterinary clinic website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/veterinarian',
    },
    label: 'Industry',
    title: 'Website for veterinary clinics in Bergen',
    description: 'Pet owners are often worried when looking for a vet, and want to quickly know how to reach you in an emergency. We build websites that reassure and make contact easy.',
    longDescription: 'A pet owner searching for a vet is often worried about their pet. The website therefore needs to build reassurance through real photos of the clinic and team, make it crystal clear how to reach you in an emergency, and make booking easy for routine check-ups and vaccinations. We build the website with exactly this as the starting point, with local SEO built in.',
    includes: [
      'Booking for check-ups and vaccinations',
      'Clear emergency contact information',
      'Presentation of treatment offerings',
      'Photos of the clinic and team that build reassurance',
      'Reviews from pet owners',
      'GDPR-secure contact form',
      'Local SEO for Bergen neighbourhoods',
      'Mobile-friendly for fast enquiries',
    ],
    process: [
      { step: '01', title: 'Mapping the clinic', description: 'We map your treatment offering, emergency routines, and the booking system you use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that builds reassurance, makes emergency contact clear, and is optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and local searches.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a veterinary clinic website cost?', a: 'A custom website for a veterinary clinic starts from NOK 15,000 excl. VAT. The price depends on the number of pages and whether you need booking-system integration.' },
      { q: 'Can pet owners book appointments directly on the website?', a: 'Yes. We integrate with the booking system your clinic uses, or set up a simple booking solution.' },
      { q: 'Is it clear how to reach you in an emergency?', a: 'Yes, we prioritise this heavily in the design. Emergency phone number and information are placed prominently at the top of the website.' },
      { q: 'Do you help with local SEO for veterinarians in Bergen?', a: 'Yes. We optimise for searches like "emergency vet Bergen" or "veterinary clinic Åsane".' },
      { q: 'Can we show reviews from pet owners?', a: 'Yes, and we recommend it — reviews from other pet owners build trust with worried customers.' },
      { q: 'How long does it take to build the website?', a: 'A standard clinic website typically takes 3–5 weeks from start to launch, depending on the number of pages and whether you need booking-system integration.' },
    ],
  },
}

export const optiker: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for optiker Bergen | Frameflow',
      description: 'Nettside for optikerbutikker i Bergen med timebestilling, brillekolleksjoner og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for optiker i Bergen | Frameflow',
      ogImageTitle: 'Nettside for optikerbutikker',
      ogImageLabel: 'Optiker',
      ogAlt: 'Nettside for optiker Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/optiker',
    },
    label: 'Bransje',
    title: 'Nettside for optiker i Bergen',
    description: 'Kunder velger optiker basert på synsundersøkelse-tilbud, brillekolleksjoner og hvor lett det er å bestille time. Vi bygger nettsider som viser frem begge deler tydelig.',
    longDescription: 'En optikerbutikk selger både en tjeneste (synsundersøkelse) og et produkt (briller, kontaktlinser). Nettsiden må derfor gjøre det enkelt å bestille time til synsundersøkelse, samtidig som den viser frem brillekolleksjoner og merker på en attraktiv måte. Vi bygger nettsiden rundt begge målene, med lokal SEO og eventuelt en enkel nettbutikk for tilbehør innebygd.',
    includes: [
      'Timebestilling for synsundersøkelse',
      'Visning av brillekolleksjoner og merker',
      'Prisoversikt for synsundersøkelse',
      'Kundeomtaler',
      'Mulighet for enkel nettbutikk for linser og tilbehør',
      'Åpningstider og lokasjon tydelig',
      'Lokal SEO for optiker-søk i Bergen',
      'Mobilvennlig design',
    ],
    process: [
      { step: '01', title: 'Kartlegging av butikken', description: 'Vi kartlegger tjenestene, kolleksjonene dere fører, og timebestillingssystemet dere bruker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som gjør bestilling enkelt og viser frem kolleksjonene attraktivt, optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på bestillinger og lokale søk.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en optikerbutikk?', a: 'En skreddersydd nettside for en optikerbutikk starter fra 15 000 kr eks. mva. Prisen avhenger av om dere ønsker nettbutikk-funksjonalitet og omfanget av produktvisning.' },
      { q: 'Kan kunder bestille time for synsundersøkelse på nettsiden?', a: 'Ja. Vi integrerer med bestillingssystemet dere allerede bruker, eller setter opp en enkel løsning.' },
      { q: 'Kan vi vise frem brillekolleksjoner på nettsiden?', a: 'Ja. Vi bygger en visning av kolleksjonene og merkene dere fører, som er enkel å oppdatere selv.' },
      { q: 'Hjelper dere med lokal SEO for optikere i Bergen?', a: 'Ja. Vi optimaliserer for søk som «optiker Bergen sentrum» eller «synsundersøkelse Åsane».' },
      { q: 'Kan vi selge kontaktlinser eller tilbehør i nettbutikk?', a: 'Ja, vi kan sette opp en enkel nettbutikk-løsning for linser og tilbehør som et tillegg til hovednettsiden.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for en optikerbutikk tar typisk 3–5 uker fra oppstart til lansering, avhengig av om dere ønsker nettbutikk-funksjonalitet og omfanget av produktvisning.' },
    ],
  },
  en: {
    meta: {
      title: 'Optician website Bergen | Frameflow',
      description: 'Websites for opticians in Bergen with eye exam booking, eyewear collections and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Optician website in Bergen | Frameflow',
      ogImageTitle: 'Websites for opticians',
      ogImageLabel: 'Optician',
      ogAlt: 'Optician website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/optician',
    },
    label: 'Industry',
    title: 'Website for opticians in Bergen',
    description: 'Customers choose an optician based on eye exam availability, eyewear collections and how easy it is to book an appointment. We build websites that showcase both clearly.',
    longDescription: 'An optician sells both a service (eye exams) and a product (glasses, contact lenses). The website therefore needs to make it easy to book an eye exam, while also showcasing eyewear collections and brands in an attractive way. We build the website around both goals, with local SEO and optionally a simple online store for accessories built in.',
    includes: [
      'Eye exam booking',
      'Display of eyewear collections and brands',
      'Pricing overview for eye exams',
      'Customer reviews',
      'Option for a simple online store for lenses and accessories',
      'Opening hours and location clearly visible',
      'Local SEO for optician searches in Bergen',
      'Mobile-friendly design',
    ],
    process: [
      { step: '01', title: 'Mapping the store', description: 'We map your services, the collections you carry, and the booking system you use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that makes booking easy and showcases collections attractively, optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on bookings and local searches.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does an optician website cost?', a: 'A custom website for an optician starts from NOK 15,000 excl. VAT. The price depends on whether you want online store functionality and the scope of product display.' },
      { q: 'Can customers book an eye exam on the website?', a: 'Yes. We integrate with the booking system you already use, or set up a simple solution.' },
      { q: 'Can we showcase eyewear collections on the website?', a: 'Yes. We build a display of the collections and brands you carry, which is easy to update yourself.' },
      { q: 'Do you help with local SEO for opticians in Bergen?', a: 'Yes. We optimise for searches like "optician Bergen city centre" or "eye exam Åsane".' },
      { q: 'Can we sell contact lenses or accessories online?', a: 'Yes, we can set up a simple online store solution for lenses and accessories as an addition to the main website.' },
      { q: 'How long does it take to build the website?', a: 'A standard optician website typically takes 3–5 weeks from start to launch, depending on whether you want online store functionality and the scope of product display.' },
    ],
  },
}

export const industries = { tannlege, eiendomsmegler, advokat, restaurant, frisor, fysioterapeut, handverker, regnskapsforer, treningssenter, bilverksted, veterinaer, optiker }

export type IndustrySlug = keyof typeof industries

export const industryList: { slug: IndustrySlug; href: string; labelNo: string; labelEn: string }[] = [
  { slug: 'tannlege', href: '/bransjer/tannlege', labelNo: 'Tannlege', labelEn: 'Dentist' },
  { slug: 'eiendomsmegler', href: '/bransjer/eiendomsmegler', labelNo: 'Eiendomsmegler', labelEn: 'Real estate agent' },
  { slug: 'advokat', href: '/bransjer/advokat', labelNo: 'Advokat', labelEn: 'Lawyer' },
  { slug: 'restaurant', href: '/bransjer/restaurant', labelNo: 'Restaurant', labelEn: 'Restaurant' },
  { slug: 'frisor', href: '/bransjer/frisor', labelNo: 'Frisør', labelEn: 'Hairdresser' },
  { slug: 'fysioterapeut', href: '/bransjer/fysioterapeut', labelNo: 'Fysioterapeut', labelEn: 'Physiotherapist' },
  { slug: 'handverker', href: '/bransjer/handverker', labelNo: 'Håndverker', labelEn: 'Tradesperson' },
  { slug: 'regnskapsforer', href: '/bransjer/regnskapsforer', labelNo: 'Regnskapsfører', labelEn: 'Accountant' },
  { slug: 'treningssenter', href: '/bransjer/treningssenter', labelNo: 'Treningssenter', labelEn: 'Gym' },
  { slug: 'bilverksted', href: '/bransjer/bilverksted', labelNo: 'Bilverksted', labelEn: 'Auto repair shop' },
  { slug: 'veterinaer', href: '/bransjer/veterinaer', labelNo: 'Veterinær', labelEn: 'Veterinarian' },
  { slug: 'optiker', href: '/bransjer/optiker', labelNo: 'Optiker', labelEn: 'Optician' },
]
