import type { ServiceContent } from '@/lib/serviceContent'

export type { ServiceContent as IndustryContent }

export const tannlege: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for tannlege Bergen – bestilling | Frameflow',
      description: 'Nettside for tannlegeklinikker i Bergen med timebestilling, pasientomtaler og lokal SEO innebygd. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for tannlege i Bergen | Frameflow',
      ogImageTitle: 'Nettside for tannleger i Bergen',
      ogImageLabel: 'Tannlege',
      ogAlt: 'Nettside for tannlege Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/tannlege',
    },
    label: 'Bransje',
    title: 'Nettside for tannlege i Bergen',
    description: 'En tannlegeklinikk lever av tillit og tilgjengelighet. Vi bygger nettsider som gjør det enkelt for pasienter å bestille time, se behandlingene deres og finne klinikken på Google – uten teknisk hodepine for deg.',
    longDescription: 'De fleste pasienter velger tannlege basert på hva de finner på Google og hvor lett det er å bestille time. En nettside for en tannlegeklinikk må derfor gjøre tre ting godt: bygge tillit gjennom profesjonelle bilder og pasientomtaler, gjøre timebestilling enkelt nok til at pasienten faktisk fullfører den, og rangere lokalt når folk søker «tannlege» pluss bydelen sin. Vi bygger nettsiden rundt akkurat disse tre målene, med lokal SEO og en trygg, GDPR-sikker løsning for pasienthenvendelser innebygd fra dag én.',
    includes: [
      'Integrasjon med timebestillingssystem',
      'Presentasjon av behandlinger og priser',
      'Bilder av klinikk og team som bygger tillit',
      'Google-anmeldelser og pasientomtaler',
      'Tydelig CTA for akutt tannlegehjelp',
      'GDPR-sikkert kontaktskjema for pasienthenvendelser',
      'Lokal SEO for bydeler i Bergen',
      'Mobilvennlig design for søk på farten',
    ],
    process: [
      { step: '01', title: 'Kartlegging av klinikken', description: 'Vi kartlegger behandlingstilbudet, timebestillingssystemet dere allerede bruker og hvilke bydeler dere vil nå med lokal SEO.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som gjør timebestilling enkelt, viser frem klinikken på en tillitvekkende måte og er teknisk optimalisert for Google fra start.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på lokale søk og henvendelser, slik at dere ser at nettsiden faktisk gir nye pasienter.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en tannlegeklinikk?', a: 'En skreddersydd nettside for en tannlegeklinikk starter fra 15 000 kr eks. mva. Prisen avhenger av antall sider, om dere trenger integrasjon mot et eksisterende timebestillingssystem, og omfanget av innhold. Vi gir alltid fast pris før oppstart.' },
      { q: 'Kan pasienter bestille time direkte på nettsiden?', a: 'Ja. Vi integrerer med timebestillingssystemet klinikken allerede bruker, eller setter opp et enkelt bestillingsskjema hvis dere ikke har et system fra før. Målet er at pasienten kan bestille time på under ett minutt.' },
      { q: 'Er nettsiden trygg for pasientopplysninger?', a: 'Ja. Kontaktskjemaer bygges med kryptert overføring og uten unødvendig lagring av helseopplysninger, i tråd med GDPR. Vi går gjennom akkurat hvilken informasjon som samles inn og hvorfor før nettsiden lanseres.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard klinikknettside tar typisk 3–5 uker fra oppstart til lansering, avhengig av hvor raskt vi får tilgang til bilder, tekster og eventuell integrasjon mot timebestillingssystem.' },
      { q: 'Kan vi vise frem pasientomtaler på nettsiden?', a: 'Ja, og vi anbefaler det sterkt – pasientomtaler er noe av det som påvirker valg av tannlege mest. Vi henter inn Google-anmeldelser automatisk eller viser frem utvalgte omtaler dere har fått tillatelse til å dele.' },
      { q: 'Hjelper dere med lokal SEO for tannleger i Bergen?', a: 'Ja, det er en kjerneleveranse. Vi optimaliserer for søk som «tannlege Bergenhus» eller «tannlege Åsane», setter opp Google Business Profile riktig, og sørger for at NAP-informasjonen (navn, adresse, telefon) er konsistent overalt.' },
    ],
  },
  en: {
    meta: {
      title: 'Dentist website Bergen – booking & SEO | Frameflow',
      description: 'Websites for dental clinics with online booking, patient reviews and local SEO built in. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Dentist website in Bergen | Frameflow',
      ogImageTitle: 'Websites for dental clinics',
      ogImageLabel: 'Dentist',
      ogAlt: 'Dentist website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/dentist',
    },
    label: 'Industry',
    title: 'Website for dentists in Bergen',
    description: 'A dental clinic lives on trust and accessibility. We build websites that make it easy for patients to book an appointment, see your treatments, and find the clinic on Google — without the technical headache for you.',
    longDescription: 'Most patients choose a dentist based on what they find on Google and how easy it is to book an appointment. A dental clinic website therefore needs to do three things well: build trust through professional photos and patient reviews, make booking simple enough that patients actually complete it, and rank locally when people search "dentist" plus their neighbourhood. We build the website around exactly these three goals, with local SEO and a secure, GDPR-compliant approach to patient enquiries built in from day one.',
    includes: [
      'Integration with your booking system',
      'Clear presentation of treatments and pricing',
      'Clinic and team photos that build trust',
      'Google reviews and patient testimonials',
      'Clear call-to-action for urgent dental care',
      'GDPR-secure contact form for patient enquiries',
      'Local SEO for Bergen neighbourhoods',
      'Mobile-friendly design for on-the-go searches',
    ],
    process: [
      { step: '01', title: 'Mapping the clinic', description: 'We map your treatment offering, the booking system you already use, and which neighbourhoods you want to reach with local SEO.' },
      { step: '02', title: 'Design and development', description: 'We build a website that makes booking simple, presents the clinic in a trust-building way, and is technically optimised for Google from the start.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on local searches and enquiries, so you can see the website is actually bringing in new patients.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a dental clinic website cost?', a: 'A custom website for a dental clinic starts from NOK 15,000 excl. VAT. The price depends on the number of pages, whether you need integration with an existing booking system, and the scope of content. We always give a fixed price before starting.' },
      { q: 'Can patients book appointments directly on the website?', a: 'Yes. We integrate with the booking system your clinic already uses, or set up a simple booking form if you don’t have one. The goal is that a patient can book an appointment in under a minute.' },
      { q: 'Is the website secure for patient information?', a: 'Yes. Contact forms are built with encrypted transmission and without unnecessary storage of health data, in line with GDPR. We review exactly what information is collected and why before the site launches.' },
      { q: 'How long does it take to build the website?', a: 'A standard clinic website typically takes 3–5 weeks from start to launch, depending on how quickly we receive photos, copy, and any booking-system integration.' },
      { q: 'Can we show patient reviews on the website?', a: 'Yes, and we strongly recommend it — patient reviews are one of the biggest factors in choosing a dentist. We pull in Google reviews automatically or feature selected testimonials you have permission to share.' },
      { q: 'Do you help with local SEO for dentists in Bergen?', a: 'Yes, it is a core part of the deliverable. We optimise for searches like "dentist Bergenhus" or "dentist Åsane", set up Google Business Profile correctly, and ensure your NAP information (name, address, phone) is consistent everywhere.' },
    ],
  },
}

export const eiendomsmegler: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for eiendomsmegler Bergen | Frameflow',
      description: 'Nettside for eiendomsmeglere i Bergen med boligvisning, verdivurdering-skjema og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for eiendomsmegler i Bergen | Frameflow',
      ogImageTitle: 'Nettside for eiendomsmeglere',
      ogImageLabel: 'Eiendomsmegler',
      ogAlt: 'Nettside for eiendomsmegler Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/eiendomsmegler',
    },
    label: 'Bransje',
    title: 'Nettside for eiendomsmegler i Bergen',
    description: 'Boligkjøpere bestemmer seg raskt – nettsiden din må vise frem boliger på en måte som selger, og gjøre det enkelt for potensielle selgere å be om verdivurdering. Vi bygger nettsider som gjør begge deler.',
    longDescription: 'En eiendomsmeglers nettside har to helt forskjellige besøkende: boligkjøpere som vil se attraktive boliger raskt, og potensielle selgere som vurderer hvem de skal gi oppdraget til. Nettsiden må derfor både presentere boliger på en salgbar måte med bilder og video i høy kvalitet, og bygge nok tillit til at en boligselger tar kontakt for verdivurdering. Vi bygger nettsiden rundt begge målgruppene, med lokal SEO for bydelene dere jobber i og en rask, mobilvennlig opplevelse for boligsøk.',
    includes: [
      'Presentasjon av boliger til salgs',
      'Skjema for gratis verdivurdering',
      'Visningskalender og kontaktpunkt for interessenter',
      'Høykvalitets bilde- og videovisning av boliger',
      'Meglerprofil som bygger tillit',
      'Lokal SEO for bydeler i Bergen',
      'Rask lasting optimalisert for boligsøk på mobil',
      'Integrasjon med annonseringsplattformer',
    ],
    process: [
      { step: '01', title: 'Kartlegging av kontoret', description: 'Vi kartlegger hvilke bydeler dere jobber i, hvordan dere annonserer boliger i dag, og hva som skal til for at en potensiell selger tar kontakt.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som viser frem boliger på en salgbar måte, gjør verdivurdering-skjemaet lett å finne, og er teknisk optimalisert for lokale søk.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og lokale rangeringer, slik at dere ser hvilke søk som faktisk gir nye oppdrag.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et meglerkontor?', a: 'En skreddersydd nettside for et eiendomsmeglerkontor starter fra 15 000 kr eks. mva. Prisen avhenger av antall sider, hvor mange meglerprofiler som skal presenteres, og om dere trenger integrasjon mot annonseringsplattformer.' },
      { q: 'Kan nettsiden vise boliger til salgs automatisk?', a: 'Ja. Vi setter opp en løsning som presenterer boligene deres tydelig, enten manuelt oppdatert eller integrert med systemet dere allerede annonserer gjennom, avhengig av hva som passer kontoret best.' },
      { q: 'Kan vi ha et skjema for gratis verdivurdering?', a: 'Ja – dette er en av de viktigste elementene på en meglernettside, siden det er hovedveien potensielle selgere tar kontakt på. Vi plasserer det synlig og gjør det raskt å fylle ut.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et meglerkontor tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall meglerprofiler og eventuell integrasjon med annonseringssystemer.' },
      { q: 'Hjelper dere med lokal SEO for eiendomsmeglere i Bergen?', a: 'Ja. Vi optimaliserer for søk som «eiendomsmegler Fana» eller «selge bolig Bergenhus», og sørger for at kontoret rangerer i de bydelene dere faktisk jobber i.' },
      { q: 'Kan dere integrere med boligannonser og visningssystem?', a: 'Ja, vi tilpasser løsningen til det annonseringssystemet eller den plattformen kontoret allerede bruker, slik at boligvisningen på nettsiden alltid er oppdatert.' },
    ],
  },
  en: {
    meta: {
      title: 'Real estate agent website Bergen | Frameflow',
      description: 'Websites for real estate agents in Bergen with property listings, valuation forms and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Real estate agent website in Bergen | Frameflow',
      ogImageTitle: 'Websites for real estate agents',
      ogImageLabel: 'Real estate',
      ogAlt: 'Real estate agent website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/real-estate-agent',
    },
    label: 'Industry',
    title: 'Website for real estate agents in Bergen',
    description: 'Home buyers decide fast — your website needs to present listings in a way that sells, and make it easy for potential sellers to request a valuation. We build websites that do both.',
    longDescription: 'A real estate agent’s website has two very different visitors: buyers who want to see attractive listings quickly, and potential sellers weighing up who to give the assignment to. The website therefore needs to both present listings in a sellable way with high-quality photos and video, and build enough trust that a seller reaches out for a valuation. We build the site around both audiences, with local SEO for the neighbourhoods you work in and a fast, mobile-friendly experience for property search.',
    includes: [
      'Presentation of listings for sale',
      'Free valuation request form',
      'Viewing calendar and contact point for interested buyers',
      'High-quality photo and video display of listings',
      'Agent profile that builds trust',
      'Local SEO for Bergen neighbourhoods',
      'Fast loading optimised for mobile property search',
      'Integration with listing platforms',
    ],
    process: [
      { step: '01', title: 'Mapping the agency', description: 'We map which neighbourhoods you work in, how you currently advertise listings, and what it takes for a potential seller to reach out.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents listings in a sellable way, makes the valuation form easy to find, and is technically optimised for local search.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and local rankings, so you can see which searches are actually bringing in new assignments.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a real estate agency website cost?', a: 'A custom website for a real estate agency starts from NOK 15,000 excl. VAT. The price depends on the number of pages, how many agent profiles need to be presented, and whether you need integration with listing platforms.' },
      { q: 'Can the website display listings automatically?', a: 'Yes. We set up a solution that presents your listings clearly, either manually updated or integrated with the system you already advertise through, depending on what suits the agency best.' },
      { q: 'Can we have a free valuation request form?', a: 'Yes — this is one of the most important elements on an agency website, since it is the main way potential sellers get in touch. We place it prominently and make it quick to fill out.' },
      { q: 'How long does it take to build the website?', a: 'A standard agency website typically takes 3–5 weeks from start to launch, depending on the number of agent profiles and any integration with listing systems.' },
      { q: 'Do you help with local SEO for real estate agents in Bergen?', a: 'Yes. We optimise for searches like "real estate agent Fana" or "sell house Bergenhus", and make sure the agency ranks in the neighbourhoods you actually work in.' },
      { q: 'Can you integrate with listing platforms and viewing systems?', a: 'Yes, we adapt the solution to the listing platform or system the agency already uses, so the property display on the website is always up to date.' },
    ],
  },
}

export const advokat: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for advokat Bergen – lokal SEO | Frameflow',
      description: 'Nettside for advokatfirmaer i Bergen som bygger tillit, presenterer rettsområder tydelig og rangerer lokalt. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for advokat i Bergen | Frameflow',
      ogImageTitle: 'Nettside for advokatfirmaer',
      ogImageLabel: 'Advokat',
      ogAlt: 'Nettside for advokat Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/advokat',
    },
    label: 'Bransje',
    title: 'Nettside for advokat i Bergen',
    description: 'Juridiske tjenester er et tillitsvalg. Nettsiden din må bygge troverdighet fra første sekund, presentere rettsområdene deres tydelig, og gjøre det trygt for potensielle klienter å ta kontakt om sensitive saker.',
    longDescription: 'Å velge advokat er et av de mest tillitsbaserte valgene folk tar – de fleste undersøker firmaet grundig på nett før de tar kontakt. Nettsiden må derfor gjøre tre ting: presentere rettsområdene og advokatenes kompetanse tydelig, bygge troverdighet gjennom ekte bilder, fagartikler og eventuelle kundeomtaler, og gi et trygt, konfidensielt kontaktpunkt for henvendelser om sensitive saker. Vi bygger nettsiden med akkurat dette som utgangspunkt, med lokal SEO for rettsområder og bydeler innebygd.',
    includes: [
      'Tydelig presentasjon av rettsområder',
      'Profilsider for hver advokat med kompetanse og bakgrunn',
      'Konfidensielt kontaktskjema for henvendelser',
      'CTA for gratis eller uforpliktende førstesamtale',
      'Fagartikler og innhold som bygger autoritet',
      'Lokal SEO for rettsområder og bydeler i Bergen',
      'Strukturert data for advokater og rettsområder',
      'Mobilvennlig design for raske henvendelser',
    ],
    process: [
      { step: '01', title: 'Kartlegging av firmaet', description: 'Vi kartlegger rettsområdene deres, hvilke advokater som skal presenteres, og hvilke søk potensielle klienter faktisk bruker.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som presenterer kompetansen deres troverdig, gjør kontakt trygt og enkelt, og er teknisk optimalisert for lokale søk innen juss.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på henvendelser og rangeringer, slik at dere ser hvilke rettsområder som faktisk gir nye klienter.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Branding', href: '/tjenester/branding' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for et advokatfirma?', a: 'En skreddersydd nettside for et advokatfirma starter fra 15 000 kr eks. mva. Prisen avhenger av antall advokatprofiler, rettsområder som skal presenteres, og om dere ønsker fagartikler som del av leveransen.' },
      { q: 'Kan potensielle klienter ta kontakt konfidensielt via nettsiden?', a: 'Ja. Kontaktskjemaer bygges med kryptert overføring, og vi går gjennom nøyaktig hvilken informasjon som samles inn slik at henvendelser om sensitive saker føles trygge å sende.' },
      { q: 'Kan vi ha egne profilsider for hver advokat?', a: 'Ja, og vi anbefaler det – potensielle klienter vil ofte vite hvem de skal snakke med og hvilken erfaring vedkommende har før de tar kontakt. Hver advokat får en egen profilside med kompetanseområder.' },
      { q: 'Hjelper dere med SEO for advokater i Bergen?', a: 'Ja. Vi optimaliserer for søk som «advokat familierett Bergen» eller «advokat arbeidsrett Åsane», og setter opp strukturert data som gjør det tydelig for Google hvilke rettsområder dere dekker.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard nettside for et advokatfirma tar typisk 3–5 uker fra oppstart til lansering, avhengig av antall advokatprofiler og om fagartikler skal skrives som del av leveransen.' },
      { q: 'Kan nettsiden bygge tillit for et fagfelt hvor troverdighet er alt?', a: 'Ja – dette er selve utgangspunktet for hvordan vi designer den. Ekte bilder fremfor stockbilder, tydelig presentasjon av erfaring og rettsområder, og fagartikler som viser kompetanse, er alle med på å bygge den tilliten juridiske tjenester er avhengige av.' },
    ],
  },
  en: {
    meta: {
      title: 'Law firm website Bergen – local SEO | Frameflow',
      description: 'Websites for law firms in Bergen that build trust, present practice areas clearly and rank locally. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Law firm website in Bergen | Frameflow',
      ogImageTitle: 'Websites for law firms',
      ogImageLabel: 'Law firm',
      ogAlt: 'Law firm website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/lawyer',
    },
    label: 'Industry',
    title: 'Website for law firms in Bergen',
    description: 'Legal services are a trust decision. Your website needs to build credibility from the first second, present your practice areas clearly, and make it safe for potential clients to reach out about sensitive matters.',
    longDescription: 'Choosing a lawyer is one of the most trust-based decisions people make — most research the firm thoroughly online before making contact. The website therefore needs to do three things: present practice areas and each lawyer’s expertise clearly, build credibility through real photos, articles and any client testimonials, and provide a safe, confidential point of contact for enquiries about sensitive matters. We build the website with exactly this as the starting point, with local SEO for practice areas and neighbourhoods built in.',
    includes: [
      'Clear presentation of practice areas',
      'Profile pages for each lawyer with expertise and background',
      'Confidential contact form for enquiries',
      'Call-to-action for a free or no-obligation initial consultation',
      'Articles and content that build authority',
      'Local SEO for practice areas and Bergen neighbourhoods',
      'Structured data for lawyers and practice areas',
      'Mobile-friendly design for quick enquiries',
    ],
    process: [
      { step: '01', title: 'Mapping the firm', description: 'We map your practice areas, which lawyers should be presented, and what searches potential clients actually use.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents your expertise credibly, makes contact safe and easy, and is technically optimised for local legal searches.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on enquiries and rankings, so you can see which practice areas are actually bringing in new clients.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Branding', href: '/tjenester/branding' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a law firm website cost?', a: 'A custom website for a law firm starts from NOK 15,000 excl. VAT. The price depends on the number of lawyer profiles, practice areas to be presented, and whether you want articles included as part of the delivery.' },
      { q: 'Can potential clients get in touch confidentially through the website?', a: 'Yes. Contact forms are built with encrypted transmission, and we review exactly what information is collected so enquiries about sensitive matters feel safe to send.' },
      { q: 'Can we have individual profile pages for each lawyer?', a: 'Yes, and we recommend it — potential clients often want to know who they will be speaking with and what experience they have before making contact. Each lawyer gets their own profile page with areas of expertise.' },
      { q: 'Do you help with SEO for lawyers in Bergen?', a: 'Yes. We optimise for searches like "family law lawyer Bergen" or "employment lawyer Åsane", and set up structured data that makes it clear to Google which practice areas you cover.' },
      { q: 'How long does it take to build the website?', a: 'A standard law firm website typically takes 3–5 weeks from start to launch, depending on the number of lawyer profiles and whether articles are written as part of the delivery.' },
      { q: 'Can the website build trust for a field where credibility is everything?', a: 'Yes — this is the actual starting point for how we design it. Real photos instead of stock images, clear presentation of experience and practice areas, and articles that demonstrate expertise all help build the trust legal services depend on.' },
    ],
  },
}

export const restaurant: Record<'no' | 'en', ServiceContent> = {
  no: {
    meta: {
      title: 'Nettside for restaurant Bergen – bordbestilling | Frameflow',
      description: 'Nettside for restauranter i Bergen med bordbestilling, meny og lokal SEO. Fast pris, ingen bindingstid. Fra 15 000 kr.',
      ogTitle: 'Nettside for restaurant i Bergen | Frameflow',
      ogImageTitle: 'Nettside for restauranter',
      ogImageLabel: 'Restaurant',
      ogAlt: 'Nettside for restaurant Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/bransjer/restaurant',
    },
    label: 'Bransje',
    title: 'Nettside for restaurant i Bergen',
    description: 'De fleste gjester bestemmer seg for en restaurant basert på bilder, meny og hvor lett det er å bestille bord. Vi bygger nettsider som gjør akkurat det – raskt, visuelt og enkelt å oppdatere selv.',
    longDescription: 'En restaurantgjest tar som regel beslutningen på mobilen, ofte rett før de skal spise. Nettsiden må derfor laste raskt, vise frem menyen og maten på en fristende måte, og gjøre bordbestilling så enkelt at gjesten faktisk fullfører den i stedet for å ringe et annet sted. Vi bygger nettsiden rundt dette, med integrasjon mot bestillings- og leveringsløsninger, sosiale medier og lokal SEO for søk som «restaurant» pluss bydel eller matkategori.',
    includes: [
      'Bordbestilling integrert på nettsiden',
      'Meny som er enkel å oppdatere selv',
      'Profesjonelle bilder av mat og lokale',
      'Åpningstider og lokasjon tydelig synlig',
      'Integrasjon med levering (Wolt, Foodora m.fl.)',
      'Instagram-feed og sosiale medier-integrasjon',
      'Lokal SEO for bydeler og matkategori',
      'Rask lasting optimalisert for mobil',
    ],
    process: [
      { step: '01', title: 'Kartlegging av restauranten', description: 'Vi kartlegger konseptet, menyen, bestillings- og leveringsløsningene dere bruker, og hvilke søk gjestene faktisk skriver inn på Google.' },
      { step: '02', title: 'Design og utvikling', description: 'Vi bygger en nettside som viser frem maten fristende, gjør bordbestilling raskt, og er teknisk optimalisert for lokale søk og rask lasting på mobil.' },
      { step: '03', title: 'Lansering og oppfølging', description: 'Etter lansering følger vi opp med rapportering på bestillinger og lokale søk, slik at dere ser hva som faktisk fyller bordene.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Foto og video', href: '/tjenester/foto-og-videografi' },
      { title: 'Sosiale medier', href: '/tjenester/sosiale-medier' },
    ],
    pricingFrom: '15 000 kr',
    faqs: [
      { q: 'Hva koster en nettside for en restaurant?', a: 'En skreddersydd nettside for en restaurant starter fra 15 000 kr eks. mva. Prisen avhenger av om dere trenger bordbestillingsintegrasjon, hvor mange sider dere ønsker, og omfanget av foto/video.' },
      { q: 'Kan gjester bestille bord direkte på nettsiden?', a: 'Ja. Vi integrerer med bordbestillingssystemet dere allerede bruker, eller setter opp en enkel løsning hvis dere ikke har en fra før, slik at gjesten bestiller bord uten å måtte ringe.' },
      { q: 'Kan vi oppdatere menyen selv?', a: 'Ja, det er en forutsetning. Menyen bygges slik at dere selv kan endre retter og priser når som helst, uten å måtte kontakte en utvikler.' },
      { q: 'Hjelper dere med lokal SEO for restauranter i Bergen?', a: 'Ja. Vi optimaliserer for søk som «restaurant Bryggen» eller «sushi Bergen sentrum», og setter opp Google Business Profile med riktige åpningstider og bilder.' },
      { q: 'Kan dere integrere levering og sosiale medier?', a: 'Ja, vi kobler på levering gjennom Wolt, Foodora eller lignende tjenester, og setter opp en Instagram-feed direkte på nettsiden slik at den alltid viser ferskt innhold.' },
      { q: 'Hvor lang tid tar det å lage nettsiden?', a: 'En standard restaurantnettside tar typisk 3–5 uker fra oppstart til lansering, avhengig av bordbestillingsintegrasjon og hvor raskt vi får bilder og menyinnhold.' },
    ],
  },
  en: {
    meta: {
      title: 'Restaurant website Bergen – table booking | Frameflow',
      description: 'Websites for restaurants in Bergen with table booking, menu and local SEO. Fixed price, no lock-in. From NOK 15,000.',
      ogTitle: 'Restaurant website in Bergen | Frameflow',
      ogImageTitle: 'Websites for restaurants',
      ogImageLabel: 'Restaurant',
      ogAlt: 'Restaurant website Bergen – Frameflow',
      canonical: 'https://www.frameflow.no/en/industries/restaurant',
    },
    label: 'Industry',
    title: 'Website for restaurants in Bergen',
    description: 'Most guests decide on a restaurant based on photos, the menu and how easy it is to book a table. We build websites that do exactly that — fast, visual and easy to update yourself.',
    longDescription: 'A restaurant guest usually makes the decision on their phone, often right before they want to eat. The website therefore needs to load fast, present the menu and food in an appetising way, and make table booking simple enough that the guest actually completes it instead of calling somewhere else. We build the website around this, with integration for ordering/delivery platforms, social media, and local SEO for searches like "restaurant" plus neighbourhood or cuisine type.',
    includes: [
      'Table booking integrated on the website',
      'Menu that is easy to update yourself',
      'Professional photos of food and interior',
      'Opening hours and location clearly visible',
      'Integration with delivery (Wolt, Foodora, etc.)',
      'Instagram feed and social media integration',
      'Local SEO for neighbourhoods and cuisine type',
      'Fast loading optimised for mobile',
    ],
    process: [
      { step: '01', title: 'Mapping the restaurant', description: 'We map your concept, menu, the ordering and delivery platforms you use, and what guests actually search for on Google.' },
      { step: '02', title: 'Design and development', description: 'We build a website that presents the food appetisingly, makes table booking fast, and is technically optimised for local search and fast mobile loading.' },
      { step: '03', title: 'Launch and follow-up', description: 'After launch we follow up with reporting on bookings and local searches, so you can see what is actually filling the tables.' },
    ],
    relatedServices: [
      { title: 'Web design', href: '/tjenester/webdesign' },
      { title: 'SEO', href: '/tjenester/seo' },
      { title: 'Photo & video', href: '/tjenester/foto-og-videografi' },
      { title: 'Social media', href: '/tjenester/sosiale-medier' },
    ],
    pricingFrom: 'NOK 15,000',
    faqs: [
      { q: 'How much does a restaurant website cost?', a: 'A custom website for a restaurant starts from NOK 15,000 excl. VAT. The price depends on whether you need table-booking integration, how many pages you want, and the scope of photo/video.' },
      { q: 'Can guests book a table directly on the website?', a: 'Yes. We integrate with the table-booking system you already use, or set up a simple solution if you don’t have one, so guests can book without having to call.' },
      { q: 'Can we update the menu ourselves?', a: 'Yes, that is a requirement. The menu is built so you can change dishes and prices yourself at any time, without contacting a developer.' },
      { q: 'Do you help with local SEO for restaurants in Bergen?', a: 'Yes. We optimise for searches like "restaurant Bryggen" or "sushi Bergen city centre", and set up Google Business Profile with correct opening hours and photos.' },
      { q: 'Can you integrate delivery and social media?', a: 'Yes, we connect delivery through Wolt, Foodora or similar services, and set up an Instagram feed directly on the website so it always shows fresh content.' },
      { q: 'How long does it take to build the website?', a: 'A standard restaurant website typically takes 3–5 weeks from start to launch, depending on table-booking integration and how quickly we receive photos and menu content.' },
    ],
  },
}

export const industries = { tannlege, eiendomsmegler, advokat, restaurant }

export type IndustrySlug = keyof typeof industries

export const industryList: { slug: IndustrySlug; href: string; labelNo: string; labelEn: string }[] = [
  { slug: 'tannlege', href: '/bransjer/tannlege', labelNo: 'Tannlege', labelEn: 'Dentist' },
  { slug: 'eiendomsmegler', href: '/bransjer/eiendomsmegler', labelNo: 'Eiendomsmegler', labelEn: 'Real estate agent' },
  { slug: 'advokat', href: '/bransjer/advokat', labelNo: 'Advokat', labelEn: 'Lawyer' },
  { slug: 'restaurant', href: '/bransjer/restaurant', labelNo: 'Restaurant', labelEn: 'Restaurant' },
]
